d2iq/ui-kit

- package-lock.json
- package.json
Use storybook-deployer to make UI Kit accessible through URL.
https://dcos-labs.github.io/ui-kit/
Closes DCOS-21776
> feat: add GH pages

- package-lock.json
- package.json
- scripts/create-component
- scripts/templates/component/Component.test.tsx
- scripts/templates/component/Component.tsx
- scripts/templates/component/README.md
- scripts/templates/component/index.ts
- scripts/templates/component/stories/Component.stories.tsx
- scripts/templates/component/style.ts
- tslint.json
Add script to generate component based on template.
Run npm run create:component -- NewComponentName
Closes DCOS-21786
> feat: script to generate component

- .dockerignore
- Dockerfile
- Jenkinsfile
- package.json
> DCOS-21772: add CI/CD

- package-lock.json
- package.json
<details><summary><strong>chore(package.json): add commitizen config</strong></summary><hr/>
This adds the conventional changelog config for commitizen.
[commitizen](https://github.com/commitizen/cz-cli)
</details>
---
Commit:
07ef6ee904ed849b1cd75f38c0338bd44055af59
> Add Commitizen config

- components/badge/style.ts
- shared/styles/color.ts
- shared/styles/typography.ts
This PR only add types to property names and remove the `"` in some places.
> refactor: add more type checking to core

- jest.config.json
- package-lock.json
- package.json
- testHelper/setupTests.ts
<details><summary><strong>chore(enzyme): add enzyme package</strong></summary><hr/>
Add the enzyme package and add the setup config for enzyme.
</details>
---
Commit:
38e19b4318853f18414ea8c5e2eb6037ef72f7e3
> Add Enzyme and jest setup file

- Jenkinsfile
looks like someone deleted the old one…
> chore(ci): fix github token credentials ID

- packages/clickable/README.md
- packages/clickable/components/clickable.tsx
- packages/clickable/index.ts
- packages/clickable/stories/clickable.stories.tsx
- packages/clickable/style.ts
- packages/clickable/tests/clickable.test.tsx
<details><summary><strong>feat(clickable): add clickable component</strong></summary><hr/>
This adds a clickable component which adds click specific attributes to a child element and is using
a11y best practices.
Close DCOS-22331
</details>
---
Commit:
a5ddbf3b3a56fdf411dbf7be1cb7d3bbf0507b33
<details><summary><strong>docs(clickable): add clickable documentation</strong></summary><hr/>
This adds the documentation for the clickable component.
</details>
---
Commit:
d1c49bbc92ea2f0a0de4119bfb55c6a9f91e37e5
> DCOS-22331: Add Clickable Component

- packages/table/tests/Table.test.tsx
This fixes an issue with the types in the tests.
<details><summary><strong>fix(table): fix table typings</strong></summary><hr/>
This fixes and issue where there was a type error in the tests. Also fixes some internal typing
issue
</details>
---
Commit:
60f9368e9f148ca102b87f457cefa818073fa89a
> Fix table test typing

- package.json
<details><summary><strong>fix: fix dist typings in package json file</strong></summary><hr/>
</details>
---
Commit:
deb1f9e2d967db1b2410ede09b9ee5fb1012308d
> Fix typings field in package.json

- packages/table/components/Column.tsx
<details><summary><strong>feat(table): export width args interface</strong></summary><hr/>
export IWidthArgs interface from Column
</details>
---
Commit:
a42cf0f37ca2702b38ed35859d31df30bad8566d
> feat(table): export width args interface

- .gitignore
- CHANGELOG.md
- package-lock.json
- package.json
> chore: add storybook-static to gitignore

- packages/table/components/Table.tsx
- packages/table/stories/Table.stories.tsx
- packages/table/tests/Table.test.tsx
- packages/table/tests/__snapshots__/Table.test.tsx.snap
To test please see the new storybook entry for Table > changing values
> DCOS-39066: Allow table to deal with dynamic data

- packages/index.ts
- packages/shared/styles/global.ts
- packages/table/components/Table.tsx
- packages/table/stories/Table.stories.tsx
- packages/table/style.ts
- packages/table/tests/__snapshots__/Table.test.tsx.snap
Add table initial styles.
Closes DCOS-39532
> DCOS-39532: feat: table style

- packages/index.ts
- packages/table/components/NumberCell.tsx
- packages/table/index.ts
- packages/table/stories/Table.stories.tsx
This adds a NumberCell component that is right aligned.
This is my first time modifying the ui kit, so please tell me if I missed something.
Related Jira: https://jira.mesosphere.com/browse/DCOS-39830
> DCOS-39830: Create NumberCell in the UI Kit

- packages/shared/styles/color.ts
- packages/shared/tests/color.test.tsx
This provides a function to convert hex colors to rgba colors
> feat(color): add function to convert hex colors to rgba

- renovate.json
This will group all packages for renovate and will only create a single pull request
for missing dependencies.
> Group all renovate apps

- packages/badge/tests/__snapshots__/badgeButton.test.tsx.snap
- packages/clickable/components/clickable.tsx
- packages/clickable/index.ts
- packages/clickable/style.ts
- packages/index.ts
- packages/toggleContent/README.md
- packages/toggleContent/components/toggleContent.tsx
- packages/toggleContent/index.ts
- packages/toggleContent/stories/toggleContent.stories.tsx
- packages/toggleContent/style.ts
- packages/toggleContent/tests/__snapshots__/toggleContent.test.tsx.snap
- packages/toggleContent/tests/toggleContent.test.tsx
Add toggle component used to switch between two
elements (String or JSX).
Closes DCOS-40043
> DCOS-40043: toggle component

- package-lock.json
- package.json
<p>This Pull Request updates devDependency <code>@types/node</code> (<a href="https://renovatebot.com/gh/DefinitelyTyped/DefinitelyTyped">source</a>) from <code>v10.7.1</code> to <code>v10.9.1</code></p>
<p><details><br />
<summary>Release Notes</summary></p>
<h3 id="v1091httpsgithubcomdefinitelytypeddefinitelytypedcompare374598de675780b1312912d43dff88f9fbfcf0d8ae9730b579ed04cb3d799fc45dfb5cff0c756ab6"><a href="https://renovatebot.com/gh/DefinitelyTyped/DefinitelyTyped/compare/374598de675780b1312912d43dff88f9fbfcf0d8…ae9730b579ed04cb3d799fc45dfb5cff0c756ab6"><code>v10.9.1</code></a></h3>
<p><a href="https://renovatebot.com/gh/DefinitelyTyped/DefinitelyTyped/compare/374598de675780b1312912d43dff88f9fbfcf0d8…ae9730b579ed04cb3d799fc45dfb5cff0c756ab6">Compare Source</a></p>
<hr />
<h3 …
> chore(deps): update dependency @types/node to v10.9.1

- package-lock.json
- package.json
Upgrading storybook-readme fixes this problem:
More info in this Github issue: https://github.com/tuchk4/storybook-readme/issues/96
> Fix error coming from register.js

- packages/infobox/components/InfoBox.tsx
- packages/infobox/stories/InfoBoxBanner.stories.tsx
- packages/infobox/stories/InfoBoxInline.stories.tsx
- packages/infobox/style.ts
- packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap
- packages/shared/styles/styleUtils/index.ts
Added styles for the InfoBox appearance variants
> DCOS-43355: InfoBox appearance variants

- packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap
- packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap
- packages/shared/styles/styleUtils/typography/color.ts
- packages/toaster/components/Toast.tsx
- packages/toaster/stories/Toaster.stories.tsx
> DCOS-43356: Toast appearance variants

- packages/infobox/style.ts
- packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap
> Infobox style update: hover state and vertical center for dismiss

- packages/appChrome/components/SidebarItemLabel.tsx
- packages/appChrome/stories/helpers/DCOSAppChrome.tsx
- packages/appChrome/style.ts
- packages/appChrome/tests/__snapshots__/AppChrome.test.tsx.snap
- packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap
- packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
- packages/shared/styles/styleUtils/layout/flexbox.ts
- packages/textInput/components/TextInput.tsx
- packages/textInput/style.ts
- packages/textInput/tests/__snapshots__/TextInput.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithIcon.test.tsx.snap
- packages/toaster/components/Toast.tsx
https://jira.mesosphere.com/browse/DCOS-46023
> [spike] Removed gutters from flexItem

- jest.config.js
- package-lock.json
- package.json
- packages/dropdownable/README.md
- packages/dropdownable/components/DropdownContents.tsx
- packages/dropdownable/components/Dropdownable.tsx
- packages/dropdownable/index.ts
- packages/dropdownable/stories/Dropdownable.stories.tsx
- packages/dropdownable/stories/helpers/DropdownStory.tsx
- packages/dropdownable/stories/helpers/DropdownStoryFit.tsx
- packages/dropdownable/stories/helpers/DropdownStuffContainer.tsx
- packages/dropdownable/tests/Dropdownable.test.tsx
- packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
- packages/index.ts
- packages/shared/components/Overlay.tsx
- packages/utilities/resizeEventManager.ts
- packages/utilities/tests/resizeEventManager.test.ts
Dropdownable is a utility component that facilitates a simple dropdownable interaction: if the open prop is true, a dropdown component prop is rendered relative to the position of the Dropdownable's children according to a list of preferences and available space. When the user clicks outside of the component, it is hidden. The dropdown is rendered using an overlay that is appended to the document body so it should appear on top of everything else.
~You can also specify through a matchWidth prop that the dropdown should match the width of the thing it appears to drop from.~
One key decision I made was to eagerly render the contents of the dropdown onto the dom, hidden, so that it can be measured for viewport fit when it is shown. Without this eager rendering, we would have to rely on …
> DCOS-45314: Dropdownable

- package.json
- packages/button/components/ButtonBase.tsx
- packages/button/style.ts
- packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
- packages/design-tokens/properties/color/border.json
- packages/design-tokens/scripts/transforms.js
- packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
- packages/index.ts
- packages/modal/README.md
- packages/modal/components/DialogModal.tsx
- packages/modal/components/DialogModalWithFooter.tsx
- packages/modal/components/FullscreenModal.tsx
- packages/modal/components/FullscreenModalHeader.tsx
- packages/modal/components/LargeDialogModal.tsx
- packages/modal/components/LargeDialogModalWithFooter.tsx
- packages/modal/components/ModalBase.tsx
- packages/modal/components/ModalContents.tsx
- packages/modal/components/SmallDialogModal.tsx
- packages/modal/components/SmallDialogModalWithFooter.tsx
- packages/modal/index.ts
- packages/modal/stories/Modal.stories.tsx
- packages/modal/stories/helpers/ModalStoryContainer.tsx
- packages/modal/stories/helpers/modalContents.tsx
- packages/modal/style.ts
- packages/modal/tests/Modal.test.tsx
- packages/modal/tests/__snapshots__/Modal.test.tsx.snap
- packages/shared/styles/styleUtils/layout/flexbox.ts
- packages/shared/styles/typography.ts
> DCOS-44053: added Modal components

- .storybook/config.js
- package-lock.json
- package.json
- packages/table/components/Table.tsx
- tslint-a11y.js
- tslint.json
Added a subset of a11y linting rules from [Microsoft's tslint rules](https://github.com/Microsoft/tslint-microsoft-contrib), and enabled Storybook's a11y panel
> [spike] Add a11y linting

- packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
- packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
- packages/modal/tests/__snapshots__/Modal.test.tsx.snap
- packages/shared/styles/styleUtils/typography/color.ts
- packages/textInput/tests/__snapshots__/TextInput.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithIcon.test.tsx.snap
https://jira.mesosphere.com/browse/DCOS-46031
> [spike] Improved usage for tintSVG style utility

- package.json
- packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap
- packages/checkboxInput/README.md
- packages/checkboxInput/components/CheckboxInput.tsx
- packages/checkboxInput/index.ts
- packages/checkboxInput/stories/CheckboxInput.stories.tsx
- packages/checkboxInput/stories/helpers/CheckboxStoryHelper.tsx
- packages/checkboxInput/style.ts
- packages/checkboxInput/tests/CheckboxInput.test.tsx
- packages/checkboxInput/tests/__snapshots__/CheckboxInput.test.tsx.snap
- packages/design-tokens/properties/color/aliases.json
- packages/index.ts
- packages/shared/components/FormFieldWrapper.tsx
- packages/shared/styles/formStyles.ts
- packages/shared/styles/styleUtils/index.ts
- packages/shared/styles/styleUtils/resets/fieldsetReset.ts
- packages/shared/styles/styleUtils/resets/listReset.ts
- packages/toaster/tests/__snapshots__/Toast.test.tsx.snap
- packages/toggleInput/components/ToggleInput.tsx
- packages/toggleInput/index.ts
- packages/toggleInput/tests/ToggleInput.test.tsx
- packages/toggleInput/tests/__snapshots__/ToggleInput.test.tsx.snap
- packages/toggleInputList/README.md
- packages/toggleInputList/components/ToggleInputList.tsx
- packages/toggleInputList/index.ts
- packages/toggleInputList/stories/ToggleInputList.stories.tsx
- packages/toggleInputList/stories/helpers/ToggleInputListStoryHelper.tsx
- packages/toggleInputList/tests/ToggleInputList.test.tsx
- packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap
Added a checkbox component and a component for rendering a fieldset with a list of checkbox components.
**Checkbox component**
**ToggleInputList component**
> DCOS-47380: Checkbox component

- scripts/templates/component/components/Component.tsx
`IComponentProps` will now just be `ComponentProps`
> [spike] Updated component generator template

- Jenkinsfile
this should fix the CI issue, forgot to add it before :(
> fix: add JIRA credentials to Jenkinsfile

- packages/checkboxInput/README.md
- packages/checkboxInput/components/CheckboxInput.tsx
- packages/checkboxInput/stories/CheckboxInput.stories.tsx
- packages/checkboxInput/stories/helpers/CheckboxStoryHelper.tsx
- packages/checkboxInput/tests/CheckboxInput.test.tsx
- packages/checkboxInput/tests/__snapshots__/CheckboxInput.test.tsx.snap
- packages/index.ts
- packages/table/README.md
- packages/table/components/CheckboxTable.tsx
- packages/table/components/SortableHeaderCell.tsx
- packages/table/components/Table.tsx
- packages/table/index.ts
- packages/table/stories/CheckboxTable.stories.tsx
- packages/table/stories/Table.stories.tsx
- packages/table/stories/helpers/CheckboxTableHelper.tsx
- packages/table/stories/helpers/SortableCheckboxTable.tsx
- packages/table/tests/CheckboxTable.test.tsx
- packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
- packages/table/tests/__snapshots__/SortableHeaderCell.test.tsx.snap
- packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap
This PR introduces the `CheckboxTable` component, and updates the Table documentation with relevant information about taking action on a set of rows.
This PR also introduces an indeterminate state to the `CheckboxInput` component for the checkbox that appears in the header of the checkbox column
> DCOS-41571: added a table with checkbox-selectable rows

- packages/selectInput/README.md
The SelectInput PR that merged earlier today included documentation for the props, but no content in the `README`
> chore: Added more SelectInput docs

- packages/shared/icons.tsx
React is expecting CamelCase attributes this fixes the kebab-case attributes on icon to CamelCase
> fix(icons): fix attributes from kebab-case to camel case

- package-lock.json
- packages/dropdownable/components/Dropdownable.tsx
- packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
- packages/index.ts
- packages/shared/styles/styleUtils/index.ts
- packages/shared/styles/styleUtils/modifiers/pseudoElTriangle.ts
- packages/table/style.ts
- packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
- packages/table/tests/__snapshots__/SortableHeaderCell.test.tsx.snap
- packages/tooltip/README.md
- packages/tooltip/components/Tooltip.tsx
- packages/tooltip/components/TooltipContent.tsx
- packages/tooltip/index.ts
- packages/tooltip/stories/Tooltip.stories.tsx
- packages/tooltip/style.ts
- packages/tooltip/tests/Tooltip.test.tsx
- packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
Adds a tooltip component to ui-kit
> DCOS-48147: add tooltip component

- packages/table/components/CheckboxTable.tsx
- packages/table/components/Table.tsx
- packages/table/stories/CheckboxTable.stories.tsx
- packages/table/stories/helpers/CheckboxTableHelper.tsx
- packages/table/tests/CheckboxTable.test.tsx
- packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
Added the ability to set CheckboxTable rows to be non-selectable and/or visually muted
> DCOS-48552: add the ability to disable CheckboxTable rows

- packages/button/style.ts
- packages/design-tokens/properties/layout/zIndex.json
- packages/dropdownable/components/Dropdownable.tsx
- packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
- packages/modal/style.ts
- packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
Now it should be possible to use Dropdownable within a modal. Moves z-indexes to design tokens to avoid z-index proliferation
> Dropdownable z-index

- .gitignore
- Jenkinsfile
- package.json
I'm _pretty_ sure this will work, but there's not really a way to test locally.
I tested it by running `deploy:storybook` with the same options I set in the Jenkinsfile, and it worked
> Fix Storybook deployment

- package-lock.json
- package.json
- packages/dropdowMenu/README.md
- packages/dropdowMenu/components/DropdownMenu.tsx
- packages/dropdowMenu/components/DropdownMenuItem.tsx
- packages/dropdowMenu/index.ts
- packages/dropdowMenu/style.ts
- packages/dropdowMenu/tests/DropdownMenu.test.tsx
- packages/dropdowMenu/tests/DropdownMenuItem.test.tsx
- packages/dropdowMenu/tests/__snapshots__/DropdownMenu.test.tsx.snap
- packages/dropdowMenu/tests/__snapshots__/DropdownMenuItem.test.tsx.snap
- packages/dropdownable/components/DropdownContents.tsx
- packages/dropdownable/components/Dropdownable.tsx
- packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
- packages/index.ts
- packages/shared/styles/styleUtils/index.ts
- packages/shared/styles/styleUtils/modifiers/border.ts
- packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
- packages/typeahead/README.md
- packages/typeahead/components/Typeahead.tsx
- packages/typeahead/index.ts
- packages/typeahead/stories/Typeahead.stories.tsx
- packages/typeahead/stories/helpers/FilteredListTypeahead.tsx
- packages/typeahead/stories/helpers/MultiselectTypeahead.tsx
- packages/typeahead/stories/helpers/itemMocks.tsx
- packages/typeahead/tests/Typeahead.test.tsx
- packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
> DCOS-52782: add Typeahead component

- packages/breadcrumb/README.md
- packages/breadcrumb/components/Breadcrumb.tsx
- packages/breadcrumb/index.ts
- packages/breadcrumb/stories/Breadcrumb.stories.tsx
- packages/breadcrumb/style.ts
- packages/breadcrumb/tests/Breadcrumb.test.tsx
- packages/breadcrumb/tests/__snapshots__/Breadcrumb.test.tsx.snap
This is a minimal version for a breadcrumb component.
CLOSES DCOS-54456
> DCOS-54456 feat(breadcrumb): add breadcrumb component

- packages/card/README.md
- packages/card/components/Card.tsx
- packages/card/index.ts
- packages/card/stories/Card.stories.tsx
- packages/card/style.ts
- packages/card/tests/Card.test.tsx
- packages/card/tests/__snapshots__/Card.test.tsx.snap
This provides a minimal card component which will create a div around children which has a border
and padding associated with it.
CLOSES DCOS-54460
> DCOS-54460 feat(card): add minimal card component

- packages/badge/tests/__snapshots__/badgeButton.test.tsx.snap
- packages/clickable/components/clickable.tsx
- packages/clickable/style.ts
- packages/modal/tests/__snapshots__/Modal.test.tsx.snap
- packages/toggleContent/tests/__snapshots__/toggleContent.test.tsx.snap
This adds cursor pointer to clickable items.
Testing:
This is a change to the `Clickable` component which can be tested in Storybook here: 
`?path=/story/clickable--default`
> fix(clickable): add cursor pointer to clickable elements

- packages/index.ts
- packages/textarea/README.md
- packages/textarea/components/Textarea.tsx
- packages/textarea/index.ts
- packages/textarea/stories/Textarea.stories.tsx
- packages/textarea/style.ts
- packages/textarea/tests/Textarea.test.tsx
- packages/textarea/tests/__snapshots__/Textarea.test.tsx.snap
> DCOS-54882: add textarea component

- package-lock.json
- package.json
- packages/index.ts
- packages/tabs/README.md
- packages/tabs/components/TabItem.tsx
- packages/tabs/components/Tabs.tsx
- packages/tabs/index.ts
- packages/tabs/stories/Tabs.stories.tsx
- packages/tabs/tests/Tabs.test.tsx
- packages/tabs/tests/__snapshots__/Tabs.test.tsx.snap
This adds the minimal version of a tabs component. The API look like this:
```JSX
class Example extends React.Component<{}, Partial<{ selectedIndex: number }>> {
state = { selectedIndex: 0 };
handleSelect = selectedIndex => {
this.setState({ selectedIndex });
};
render() {
const { selectedIndex } = this.state;
return (
<Tabs selectedIndex={selectedIndex} onSelect={this.handleSelect}>
<TabItem>
<TabTitle>Tab 1 Name</TabTitle>
First tab Content
</TabItem>
<TabItem>
<TabTitle>Tab 2 Name</TabTitle>
Second Tab Content
</TabItem>
</Tabs>
);
}
}
```
Depends on #337 
Part of DCOS-54459
> DCOS-54459: feat(tabs): add tabs component

- packages/index.ts
> chore: add top level package export for configuration map

- packages/icons/scripts/build.js
I implemented Daniel's feedback in [this PR](https://github.com/dcos-labs/ui-kit/pull/272), but it got overwritten at some point
> Correct bad merge on icon build script

- packages/tabs/components/Tabs.tsx
This adds the styling to tabs.
CLOSES DCOS-56024
> DCOS-56024: feat(tabs): add styling

- package-lock.json
- package.json
- packages/breadcrumb/tests/__snapshots__/Breadcrumb.test.tsx.snap
- packages/card/tests/__snapshots__/Card.test.tsx.snap
- packages/design-tokens/properties/font/lineHeight.json
- packages/design-tokens/properties/layout/containerWidths.json
- packages/dropdowMenu/tests/__snapshots__/DropdownMenuItem.test.tsx.snap
- packages/modal/tests/__snapshots__/Modal.test.tsx.snap
- packages/pageheader/tests/__snapshots__/PageHeader.test.tsx.snap
- packages/shared/styles/breakpoints.ts
- packages/shared/styles/styleUtils/index.ts
- packages/shared/styles/styleUtils/layout/handleResponsiveStyle.ts
- packages/shared/styles/styleUtils/modifiers/border.ts
- packages/shared/styles/styleUtils/modifiers/modifierUtils.ts
- packages/shared/styles/styleUtils/modifiers/padding.ts
- packages/shared/tests/handleResponnsiveStyle.test.tsx
- packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
- packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
There are no visual changes, these are just changes to lower level code (like design tokens) to support the other style utility PRs.
Just check that tests still pass and the code looks good. See other style utility PRs for additional context
> Setup work to support style utility components

- packages/index.ts
- packages/styleUtils/modifiers/README.md
- packages/styleUtils/modifiers/components/BorderedBox.tsx
- packages/styleUtils/modifiers/components/Box.tsx
- packages/styleUtils/modifiers/components/SpacingBox.tsx
- packages/styleUtils/modifiers/index.ts
- packages/styleUtils/modifiers/stories/BorderedBox.stories.tsx
- packages/styleUtils/modifiers/stories/Box.stories.tsx
- packages/styleUtils/modifiers/stories/SpacingBox.stories.tsx
- packages/styleUtils/modifiers/stories/helpers/outlineDecorator.tsx
- packages/styleUtils/modifiers/tests/BorderedBox.test.tsx
- packages/styleUtils/modifiers/tests/Box.test.tsx
- packages/styleUtils/modifiers/tests/SpacingBox.test.tsx
- packages/styleUtils/modifiers/tests/__snapshots__/BorderedBox.test.tsx.snap
- packages/styleUtils/modifiers/tests/__snapshots__/Box.test.tsx.snap
- packages/styleUtils/modifiers/tests/__snapshots__/SpacingBox.test.tsx.snap
These are the most basic style utility components to give access to simple things like adding a border or applying spacing.
These components are:
Box
SpacingBox
BorderedBox
See the README in this PR for more info
Many of these stories make use of Storybook's "Knobs" panel
> DCOS-43353: add style utility modifier components

- packages/configurationmap/README.md
- packages/configurationmap/components/ConfigurationMap.tsx
- packages/configurationmap/components/ConfigurationMapHeading.tsx
- packages/configurationmap/components/ConfigurationMapLabel.tsx
- packages/configurationmap/components/ConfigurationMapRow.tsx
- packages/configurationmap/components/ConfigurationMapRowAction.tsx
- packages/configurationmap/components/ConfigurationMapSection.tsx
- packages/configurationmap/components/ConfigurationMapValue.tsx
- packages/configurationmap/components/ConfigurationMapValueWithDefault.tsx
- packages/configurationmap/components/HashMap.tsx
- packages/configurationmap/index.ts
- packages/configurationmap/stories/ConfigurationMap.stories.tsx
- packages/configurationmap/stories/HashMap.stories.tsx
- packages/configurationmap/stories/helpers/ConfigurationMapStoryWrapper.tsx
- packages/configurationmap/style.ts
- packages/configurationmap/tests/ConfigurationMap.test.tsx
- packages/configurationmap/tests/HashMap.test.tsx
- packages/configurationmap/tests/__snapshots__/ConfigurationMap.test.tsx.snap
- packages/configurationmap/tests/__snapshots__/HashMap.test.tsx.snap
- packages/index.ts
- packages/shared/styles/styleUtils/index.ts
- packages/shared/styles/styleUtils/modifiers/visuallyHidden.ts
- packages/shared/styles/styleUtils/resets/definitionListReset.ts
- packages/table/README.md
- packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
> DCOS-54898: finished ConfigurationMap, added HashMap

- packages/card/style.ts
- packages/card/tests/__snapshots__/Card.test.tsx.snap
> DCOS-54896: finish styling the card component

- packages/styleUtils/typography/components/Text.tsx
- packages/styleUtils/typography/style.ts
- packages/styleUtils/typography/tests/__snapshots__/typographyComponents.test.tsx.snap
I wrote the style and forgot to add it 🙈
**Before:**
**After:**
> Add line-height to Text component

- packages/donutChart/components/DonutChart.tsx
- packages/donutChart/tests/__snapshots__/DonutChart.test.tsx.snap
- packages/tabs/components/Tabs.tsx
We had some react warnings triggered by errors in ui-kit
> Remove Redbox errors (for components used in kommander)

- packages/appChrome/components/SidebarItem.tsx
- packages/appChrome/components/SidebarSubMenu.tsx
- packages/appChrome/components/SidebarSubMenuItem.tsx
- packages/appChrome/stories/AppChrome.stories.tsx
- packages/appChrome/style.ts
- packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap
- packages/appChrome/types/appChromeTheme.ts
Needed for latest Konvoy/Kommander appchrome visual design: https://mesosphere.invisionapp.com/share/4DSOYVZENVB#/screens/374426634
> Make SidebarItem "active" background color themable

- package-lock.json
- package.json
- packages/button/style.ts
- packages/index.ts
- packages/segmentedControl/README.md
- packages/segmentedControl/components/SegmentedControl.tsx
- packages/segmentedControl/components/SegmentedControlButton.tsx
- packages/segmentedControl/index.ts
- packages/segmentedControl/stories/SegmentedControl.stories.tsx
- packages/segmentedControl/stories/helpers/SegmentedControlStoryHelper.tsx
- packages/segmentedControl/style.ts
- packages/segmentedControl/tests/SegmentedControl.test.tsx
- packages/segmentedControl/tests/__snapshots__/SegmentedControl.test.tsx.snap
> DCOS-57723: added a segmented control component

- .gitignore
- CONTRIBUTING.md
- Dockerfile
- Jenkinsfile
- cypress.json
- cypress/fixtures/example.json
- cypress/integration/storybook-cy.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- cypress/utils/navigateToStory.js
- package-lock.json
- package.json
- packages/appChrome/stories/AppChrome.stories.tsx
- packages/appChrome/stories/helpers/StorybookSidebarHelpers.tsx
- scripts/test-integration
CI should be read because AppChrome has a key error / warning
> Check Storybook components for console errors / warnings

- package-lock.json
- package.json
- packages/index.ts
- packages/progressbar/README.md
- packages/progressbar/components/ProgressBar.tsx
- packages/progressbar/components/ProgressBarSegmentLegend.tsx
- packages/progressbar/index.ts
- packages/progressbar/stories/ProgressBar.stories.tsx
- packages/progressbar/style.ts
- packages/progressbar/tests/ProgressBar.test.tsx
- packages/progressbar/tests/__snapshots__/ProgressBar.test.tsx.snap
- packages/styleUtils/typography/components/Text.tsx
- packages/styleUtils/typography/tests/__snapshots__/typographyComponents.test.tsx.snap
- packages/styleUtils/typography/textTypes.ts
- packages/table/components/CheckboxTable.tsx
- packages/toggleContent/components/toggleContent.tsx
- packages/utilities/components/percentage.ts
> DCOS-57915: adds ProgressBar component

- package-lock.json
- packages/card/README.md
- packages/card/components/ButtonCard.tsx
- packages/card/components/Card.tsx
- packages/card/index.ts
- packages/card/stories/ButtonCard.stories.tsx
- packages/card/style.ts
- packages/card/tests/ButtonCard.test.tsx
- packages/card/tests/__snapshots__/ButtonCard.test.tsx.snap
- packages/card/tests/__snapshots__/Card.test.tsx.snap
- packages/index.ts
- packages/toggleBox/README.md
- packages/toggleBox/components/ToggleBox.tsx
- packages/toggleBox/components/ToggleBoxGroup.tsx
- packages/toggleBox/index.ts
- packages/toggleBox/stories/ToggleBox.stories.tsx
- packages/toggleBox/stories/ToggleBoxGroup.stories.tsx
- packages/toggleBox/stories/helpers/ToggleBoxGroupStoryHelper.tsx
- packages/toggleBox/stories/helpers/ToggleBoxStoryHelper.tsx
- packages/toggleBox/tests/ToggleBox.test.tsx
- packages/toggleBox/tests/ToggleBoxGroup.test.tsx
- packages/toggleBox/tests/__snapshots__/ToggleBox.test.tsx.snap
- packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap
- packages/toggleWrapper/README.md
- packages/toggleWrapper/components/ToggleWrapper.tsx
- packages/toggleWrapper/index.ts
- packages/toggleWrapper/stories/ToggleWrapper.stories.tsx
- packages/toggleWrapper/tests/ToggleWrapper.test.tsx
- packages/toggleWrapper/tests/__snapshots__/ToggleWrapper.test.tsx.snap
These component will be used to render the selection interface for providers in Kommander
> DCOS-57983: adds ToggleBox and related component

- package-lock.json
- package.json
- packages/clicktocopybutton/README.md
- packages/clicktocopybutton/components/ClickToCopy.tsx
- packages/clicktocopybutton/components/ClickToCopyButton.tsx
- packages/clicktocopybutton/index.ts
- packages/clicktocopybutton/stories/ClickToCopyButton.stories.tsx
- packages/clicktocopybutton/stories/helpers/ClickToCopyTooltipHelper.tsx
- packages/clicktocopybutton/tests/ClickToCopyButton.test.tsx
- packages/clicktocopybutton/tests/__snapshots__/ClickToCopyButton.test.tsx.snap
- packages/codesnippet/README.md
- packages/codesnippet/components/CodeSnippet.tsx
- packages/codesnippet/index.ts
- packages/codesnippet/stories/CodeSnippet.stories.tsx
- packages/codesnippet/tests/CodeSnippet.test.tsx
- packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
- packages/tooltip/components/Tooltip.tsx
- packages/tooltip/tests/Tooltip.test.tsx
Navigate to the `ClickToCopyButton` and `CodeSnippet` stories in Storybook and confirm they're functioning as expected
> DCOS-58113: CodeSnippet and ClickToCopyButton components

- packages/appChrome/components/SidebarItem.tsx
- packages/appChrome/components/SidebarSubMenu.tsx
- packages/appChrome/components/SidebarSubMenuItem.tsx
- packages/appChrome/stories/AppChrome.stories.tsx
- packages/appChrome/style.ts
- packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap
- packages/expandable/components/Expandable.tsx
- packages/expandable/stories/Expandable.stories.tsx
Needed for https://jira.mesosphere.com/browse/DCOS-59136
> Allow sidebar items to be disabled

- packages/badge/style.ts
- packages/badge/tests/__snapshots__/badge.test.tsx.snap
- packages/badge/tests/__snapshots__/badgeButton.test.tsx.snap
- packages/tabs/components/Tabs.tsx
- packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
This changes the tab margin from s to m.
CLOSES DCOS-59470
> DCOS-59470: fix(tabs): fix tab margin

- packages/badge/style.ts
- packages/badge/tests/__snapshots__/badge.test.tsx.snap
- packages/badge/tests/__snapshots__/badgeButton.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
This changes the line height of the badge 20px by that normalizing the size of the badge to 20 px.
CLOSES DCOS-59463
> fix(badge): change line height to 20px

- packages/toggleInputList/components/ToggleInputList.tsx
- packages/toggleInputList/stories/ToggleInputList.stories.tsx
- packages/toggleInputList/tests/ToggleInputList.test.tsx
- packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap
- Added required prop to set if the listLabel should display a required
asterisk. This is so that the input can be used in the same way as other
form inputs
- Add labelAppearance to control the style of the listLabel in a similar
way that we style other input labels.
> feat(ToggleListInput): add required and labelAppearance

- packages/appChrome/style.ts
- packages/appChrome/tests/__snapshots__/AppChrome.test.tsx.snap
- packages/index.ts
- packages/styleUtils/layout/flexbox/components/Flex.tsx
- packages/styleUtils/layout/flexbox/components/FlexItem.tsx
- packages/table/README.md
- packages/table/components/Table.tsx
- packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
- packages/table/tests/__snapshots__/Table.test.tsx.snap
- packages/tableView/README.md
- packages/tableView/components/TableView.tsx
- packages/tableView/components/TableViewBody.tsx
- packages/tableView/components/TableViewHeader.tsx
- packages/tableView/index.ts
- packages/tableView/stories/TableView.stories.tsx
- packages/tableView/stories/helpers/DemoTable.tsx
This came out of [DCOS-60082](https://jira.mesosphere.com/browse/DCOS-60082). I have a branch where I've resolved that ticket using the components in this PR.
> Add a helper component for table layouts

- packages/tabs/components/Tabs.tsx
- packages/tabs/stories/Tabs.stories.tsx
- packages/tabs/style.ts
- packages/tabs/tests/Tabs.test.tsx
- packages/tabs/tests/__snapshots__/Tabs.test.tsx.snap
> DCOS-57973: adds support for vertical tabs

- packages/table/components/HeaderCell.tsx
- packages/table/stories/Table.stories.tsx
- packages/table/style.ts
- packages/table/tests/__snapshots__/Cell.test.tsx.snap
- packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
- packages/table/tests/__snapshots__/SortableHeaderCell.test.tsx.snap
> Enable lower case HeaderCell

- packages/appChrome/style.ts
- packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap
1. Go to `packages/appChrome/components/Sidebar.tsx`.
2. Add a container with small height.
```
const Container = styled("div")`
height: 200px;
`;
```
3. Wrap it around the return in the render like this:
```
return (
<Container>
<ThemeProvider theme={adjustedTheme}>
<StyledSidebar className={sidebarAnimator}>
<StyledNav className={sidebar}>{children}</StyledNav>
</StyledSidebar>
</ThemeProvider>
</Container>
);
```
4. Open any of the bigger sidebars, for example [`Sidebar w/ items (w/ icons)`](http://localhost:6006/?path=/story/appchrome--sidebar-w-items-w-icons).
5. Verify that the sidebar is scrollable.
> Make sidebar scrollable

- packages/table/components/Cell.tsx
- packages/table/components/HeaderCell.tsx
- packages/table/components/SortableHeaderCell.tsx
- packages/table/tests/__snapshots__/Cell.test.tsx.snap
- packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
- packages/table/tests/__snapshots__/SortableHeaderCell.test.tsx.snap
Go to a [table that should be sortable](http://localhost:6006/?path=/story/table--with-sortable-column), and verify that it is.
I accidentally wrote scrollable instead of sortable in the branch name and commit message.
> Fix sortable table

- packages/table/components/Cell.tsx
- packages/table/components/HeaderCell.tsx
- packages/table/components/SortableHeaderCell.tsx
- packages/table/tests/__snapshots__/Cell.test.tsx.snap
- packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
- packages/table/tests/__snapshots__/SortableHeaderCell.test.tsx.snap
See https://github.com/dcos-labs/ui-kit/pull/432
> Table cell capitalization (new PR b/c CI issues)

- packages/button/components/ResetButton.tsx
- packages/button/index.ts
- packages/index.ts
- packages/shared/styles/formStyles.ts
- packages/textInput/README.md
- packages/textInput/components/TextInputWithBadges.tsx
- packages/textInput/components/TextInputWithButtons.tsx
- packages/textInput/components/TextInputWithIcon.tsx
- packages/textInput/index.ts
- packages/textInput/stories/TextInputWithButtons.stories.tsx
- packages/textInput/tests/TextInputWithButtons.test.tsx
- packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithButtons.test.tsx.snap
- packages/textInputButton/README.md
- packages/textInputButton/components/TextInputButton.tsx
- packages/textInputButton/index.ts
> Add components to support text inputs with buttons inside

- packages/button/README.md
- packages/button/components/ResetButton.tsx
- packages/button/stories/ResetButton.stories.tsx
- packages/button/style.ts
- packages/index.ts
- packages/textInput/tests/__snapshots__/TextInputWithButtons.test.tsx.snap
> DCOS-61568: document and export ResetButton component

- packages/index.ts
- packages/inlineBorderedItems/README.md
- packages/inlineBorderedItems/components/InlineBorderedItems.tsx
- packages/inlineBorderedItems/index.ts
- packages/inlineBorderedItems/stories/inlineBorderedItems.stories.tsx
- packages/inlineBorderedItems/style.ts
- packages/inlineBorderedItems/tests/__snapshots__/inlineBorderedItems.test.tsx.snap
- packages/inlineBorderedItems/tests/inlineBorderedItems.test.tsx
> DCOS-61095: adds InlineBorderedItems component

- packages/emptyState/README.md
- packages/emptyState/components/EmptyState.tsx
- packages/emptyState/components/EmptyStateActions.tsx
- packages/emptyState/components/EmptyStateWithGraphic.tsx
- packages/emptyState/components/EmptyStateWrapper.tsx
- packages/emptyState/index.ts
- packages/emptyState/stories/emptyState.stories.tsx
- packages/emptyState/stories/emptyStateWithGraphic.stories.tsx
- packages/emptyState/style.ts
- packages/emptyState/tests/__snapshots__/emptyState.test.tsx.snap
- packages/emptyState/tests/__snapshots__/emptyStateWithGraphic.test.tsx.snap
- packages/emptyState/tests/emptyState.test.tsx
- packages/emptyState/tests/emptyStateWithGraphic.test.tsx
- packages/index.ts
> DCOS-61091 & 61090: empty state components

- packages/index.ts
- packages/loadingIndicator/README.md
- packages/loadingIndicator/components/InlineLoadingIndicator.tsx
- packages/loadingIndicator/components/SectionLoadingIndicator.tsx
- packages/loadingIndicator/index.ts
- packages/loadingIndicator/stories/loadingIndicator.stories.tsx
- packages/loadingIndicator/style.ts
- packages/loadingIndicator/tests/__snapshots__/loadingIndicator.test.tsx.snap
- packages/loadingIndicator/tests/loadingIndicator.test.tsx
> DCOS-61479: add components and docs for loading indicators

- packages/toggleBox/components/ToggleBox.tsx
- packages/toggleBox/components/ToggleBoxGroup.tsx
- packages/toggleBox/style.ts
- packages/toggleBox/tests/__snapshots__/ToggleBox.test.tsx.snap
- packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap
> fix(toggleboxgroup): makes toggleboxes the same height

- packages/formStructure/README.md
- packages/formStructure/components/FormMessage.tsx
- packages/formStructure/components/FormSection.tsx
- packages/formStructure/components/FormSectionBody.tsx
- packages/formStructure/components/FormSectionFooter.tsx
- packages/formStructure/components/FormSectionHeader.tsx
- packages/formStructure/components/FormSubSection.tsx
- packages/formStructure/components/FormTitle.tsx
- packages/formStructure/index.ts
- packages/formStructure/stories/formStructure.stories.tsx
- packages/formStructure/style.ts
- packages/formStructure/tests/__snapshots__/formStructure.test.tsx.snap
- packages/formStructure/tests/formStructure.test.tsx
- packages/formStructure/tests/formSubSection.test.tsx
- packages/infobox/components/InfoBox.tsx
- packages/styleUtils/typography/textTypes.ts
These are the components that make up the structure of a form at a macro level. There are additional subtasks on the parent ticket ([DCOS-61100](https://jira.mesosphere.com/browse/DCOS-61100)) to create other helpful form components.
> DCOS-61101: top-level form structure components

- packages/dropdownMenu/components/DropdownMenu.tsx
- packages/dropdownMenu/stories/Dropdown.stories.tsx
- packages/dropdownMenu/tests/__snapshots__/DropdownMenu.test.tsx.snap
- packages/popover/components/Popover.tsx
- packages/popover/tests/__snapshots__/Popover.test.tsx.snap
- packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
> Apply an optional maximum width to a DropdownMenu

- packages/configurationmap/components/ConfigurationMapLabel.tsx
- packages/configurationmap/components/ConfigurationMapValue.tsx
- packages/configurationmap/stories/ConfigurationMap.stories.tsx
- packages/configurationmap/tests/__snapshots__/ConfigurationMap.test.tsx.snap
- packages/configurationmap/tests/__snapshots__/HashMap.test.tsx.snap
> Config map break word

- packages/card/README.md
- packages/card/components/ButtonCard.tsx
- packages/card/components/LinkCard.tsx
- packages/card/index.ts
- packages/card/stories/LinkCard.stories.tsx
- packages/card/style.ts
- packages/card/tests/LinkCard.test.tsx
- packages/card/tests/__snapshots__/ButtonCard.test.tsx.snap
- packages/card/tests/__snapshots__/LinkCard.test.tsx.snap
- packages/index.ts
- packages/toggleBox/tests/__snapshots__/ToggleBox.test.tsx.snap
- packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap
- packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
Adds a component for cards that go somewhere when clicked
This also includes a fix for keyboard accessibility for the ButtonCard component. Previously, the button was not "clickable" when the user pressed the enter key or the space bar.
> Add LinkCard component

- packages/icons/src/icon-product/project-inverse.svg
- packages/icons/src/icon-product/project.svg
> Add a Projects icon to the product icons

- packages/pageheader/components/PageHeaderTabs.tsx
> Add space between tabs and page header content

- package-lock.json
- package.json
- packages/appChrome/stories/helpers/StorybookSidebarHelpers.tsx
- packages/button/index.ts
- packages/configurationmap/components/ConfigurationMapHeading.tsx
- packages/configurationmap/components/ConfigurationMapRowAction.tsx
- packages/configurationmap/components/ConfigurationMapValueWithDefault.tsx
- packages/configurationmap/index.ts
- packages/dropdownMenu/index.ts
- packages/emptyState/index.ts
- packages/formStructure/components/FieldListColumn.tsx
- packages/inlineBorderedItems/index.ts
- packages/legacy/src/Dropdown/Dropdown.tsx
- packages/loadingIndicator/index.ts
- packages/modal/index.ts
- packages/progressbar/index.ts
- packages/segmentedControl/index.ts
- packages/table/components/SortableHeaderCell.tsx
- packages/table/components/Table.tsx
- packages/tabs/components/Tabs.tsx
- packages/textInput/index.ts
- packages/textarea/components/Textarea.tsx
- packages/utilities/index.ts
needed that, so we could conveniently use new typescript features.
> chore: update prettier

- packages/configurationmap/components/ConfigurationMap.tsx
- packages/configurationmap/components/ConfigurationMapHeading.tsx
- packages/configurationmap/components/ConfigurationMapSection.tsx
- packages/configurationmap/style.ts
- packages/configurationmap/tests/__snapshots__/ConfigurationMap.test.tsx.snap
- packages/configurationmap/tests/__snapshots__/HashMap.test.tsx.snap
These changes also include some spacing adjustments.
Before:
After:
> D2IQ-64547: uses typography components in ConfigMap

- packages/button/components/ButtonBase.tsx
> Fix color for button with url

- packages/table/stories/Table.stories.tsx
we don't have lowerCase as a prop on HeaderCell anymore and get an according
type error. let's fix that!
> chore: fix a bug in the table stories

- packages/index.ts
- packages/styleUtils/layout/index.ts
- packages/styleUtils/layout/stack/README.md
- packages/styleUtils/layout/stack/components/Stack.tsx
- packages/styleUtils/layout/stack/stories/stack.stories.tsx
- packages/styleUtils/layout/stack/style.ts
- packages/styleUtils/layout/stack/tests/__snapshots__/stack.test.tsx.snap
- packages/styleUtils/layout/stack/tests/stack.test.tsx
Closes [D2IQ-64873](https://jira.d2iq.com/browse/D2IQ-64873)
> D2IQ-64873: Stack component

- packages/button/README.md
- packages/button/components/ButtonBase.tsx
- packages/button/components/DangerButton.tsx
- packages/button/components/PrimaryButton.tsx
- packages/button/components/SecondaryButton.tsx
- packages/button/components/StandardButton.tsx
- packages/button/components/SuccessButton.tsx
- packages/button/stories/DefaultButton.stories.tsx
- packages/button/style.ts
- packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
- packages/configurationmap/tests/__snapshots__/ConfigurationMap.test.tsx.snap
- packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
- packages/emptyState/tests/__snapshots__/emptyState.test.tsx.snap
- packages/emptyState/tests/__snapshots__/emptyStateWithGraphic.test.tsx.snap
- packages/formStructure/tests/__snapshots__/fieldList.test.tsx.snap
- packages/fullscreenView/tests/__snapshots__/fullscreenView.test.tsx.snap
- packages/modal/tests/__snapshots__/Modal.test.tsx.snap
- packages/shared/styles/styleUtils/resets/linkReset.ts
Make sure to test in both Firefox and Chrome as some of the solutions that I tried worked only in Chrome.
> Fix PrimaryButton with url color

- packages/toggleBox/components/ToggleBoxGroup.tsx
- packages/toggleBox/stories/ToggleBoxGroup.stories.tsx
- packages/toggleBox/tests/ToggleBoxGroup.test.tsx
- packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap
> ToggleBoxGroup label

- packages/dropdownMenu/components/DropdownMenu.tsx
- packages/tabs/components/Tabs.tsx
- packages/toaster/components/Toast.tsx
- packages/toaster/components/Toaster.tsx
- packages/toaster/stories/Toaster.stories.tsx
- packages/toaster/tests/Toast.test.tsx
- packages/toaster/tests/Toaster.test.tsx
- packages/toggleBox/components/ToggleBoxGroup.tsx
- tsconfig.json
- typings/react.d.ts
because i wanted to use toasts in DCOS-UI and was interested in how stuff works, i played around with some code and thought it's worthwhile to share the results.
> iterate on toasts

- packages/table/components/Cell.tsx
- packages/table/components/HeaderCell.tsx
- packages/table/components/SortableHeaderCell.tsx
- packages/table/components/Table.tsx
- packages/table/stories/Table.stories.tsx
- packages/table/stories/helpers/SortableTable.tsx
- packages/table/style.ts
- packages/table/tests/__snapshots__/Cell.test.tsx.snap
- packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
Relates to [D2IQ-64203](https://jira.d2iq.com/browse/D2IQ-64203)
We already have this pattern in DC/OS, and we're starting to do it in Kommander. I think it makes sense to handle it in ui-kit instead of making engineers do it manually.
> Table column header with tooltip

- packages/tooltip/components/Tooltip.tsx
- packages/tooltip/tests/Tooltip.test.tsx
- packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
- packages/utilities/getFirstFocusableChildNode.ts
> D2IQ-64883: improve tooltip keyboard nav

- packages/progressbar/README.md
- packages/progressbar/components/ProgressBar.tsx
- packages/progressbar/stories/ProgressBar.stories.tsx
- packages/progressbar/tests/__snapshots__/ProgressBar.test.tsx.snap
Navigate to the "Using condensed layout" story for ProgressBar
> D2IQ-61191: ProgressBar condensed layout variant

- packages/tablev2/Table.tsx
- packages/tablev2/__snapshots__/tablev2.test.tsx.snap
- packages/tablev2/tablev2.stories.tsx
we had a bug in disabling columns before and created an SSCCE before fixing it.
here's a more readable version of that.
> chore: add a story showing that disabling cols is possible

- packages/promo/README.md
- packages/promo/__snapshots__/promos.test.tsx.snap
- packages/promo/components/PromoBanner.tsx
- packages/promo/promos.test.tsx
- packages/promo/stories/promoBanner.stories.tsx
- packages/promo/types.ts
Relates to D2IQ-68807
Check the "w/ custom background color" story under the "PromoBanner"
> D2IQ-68807: adds bg color options for the PromoBanner component

- design-guidelines/copy-and-content/date-time-formatting.md
Closes D2IQ-68510
Read the guidelines about how to deal with dates and times in D2iQ apps. I recommend reviewing using GitHub's markdown view.
Please comment if:
- anything in the guidelines is unclear
- you can think of scenarios that are not covered by these guidelines
- you disagree with anything from these guidelines
This first draft does not have any guidelines to account for translation/internationalization. I think we need to come up with some guidelines about designing for a global audience before we attempt to document how to handle global date and time formatting.
> D2IQ-68510: dates and time formatting guidelines

- design-guidelines/interactive-element-states.md
- packages/button/README.md
- packages/dropdownMenu/README.md
Closes D2IQ-68509
Read the guidelines about when we prefer to hide an action that can't be interacted with, and when to disable an action that can't be interacted with.
Please comment if:
- anything in the guidelines is unclear
- you can think of scenarios that are not covered by these guidelines
- you disagree with anything from these guidelines
We aren't rendering the contents of the README documents from `design-guidelines`.
For now, we just want to define some guidelines for designing D2iQ apps, but the plan is to improve the experience for reading our design docs by using Storybook Docs or a static site generator.
> D2IQ-68509: define UX guidelines for actions that cannot be executed

- packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
- packages/styleUtils/typography/components/MonospaceText.tsx
- packages/styleUtils/typography/tests/__snapshots__/typographyComponents.test.tsx.snap
> Correct MonospaceText font family stack

- design-guidelines/interactive-element-states.md
Closes D2IQ-69560
Read the guidelines about how we indicate various states of component interactivity.
Please comment if:
- anything in the guidelines is unclear
- you can think of scenarios that are not covered by these guidelines
- you disagree with anything from these guidelines
> D2IQ-69560: documentation for interactive element state UX

- packages/tablev2/Table.tsx
- Check the Table stories 
- Went for the simplest solution: copying the data. If this causes performance problems we need to adjust 🙈
> Table: Make sure input data is treated as read only (D2IQ-70553)

- packages/badge/README.md
- packages/badge/components/ColorCodedBadge.tsx
- packages/badge/components/badge.tsx
- packages/badge/index.ts
- packages/badge/stories/badge.stories.tsx
- packages/badge/tests/__snapshots__/colorCodedBadge.test.tsx.snap
- packages/badge/tests/colorCodedBadge.test.tsx
- packages/index.ts
Closes D2IQ-71117
Just look at Storybook
> D2IQ-71117: adds ColorCodedBadge component

- packages/index.ts
> fix: export ClickToCopyButton from packages

- packages/accordion/accordion.stories.tsx
- packages/accordion/components/AccordionContext.tsx
- packages/accordion/components/AccordionItemTitle.tsx
- packages/accordion/components/StatelessAccordion.tsx
- packages/accordion/index.ts
- packages/accordion/types.ts
- packages/index.ts
- packages/toggleInputList/stories/ToggleInputList.stories.tsx
- packages/toggleInputList/stories/helpers/ToggleInputListStoryHelper.tsx
- packages/toggleInputList/stories/helpers/toggleInputDecorator.tsx
Relates to D2IQ-70897
All the Accordion stories should still work as expected.
The StatelessAccordion story should work.
There's some shared code between Accordion and StatelessAccordion that could probably be DRY'd out.
https://share.getcloudapp.com/qGuv1Dql
> D2IQ-70897: adds StatelessAccordion component

- packages/index.ts
- packages/tablev2/MutedCell.tsx
- packages/tablev2/README.md
- packages/tablev2/__snapshots__/tablev2.test.tsx.snap
- packages/tablev2/index.ts
- packages/tablev2/tablev2.stories.tsx
- packages/tablev2/tablev2.test.tsx
Relates to D2IQ-66963
Check out the "muted cells" story in Storybook
> D2IQ-66963: MutedCell component

- packages/progressbar/components/ProgressBar.tsx
- packages/progressbar/tests/__snapshots__/ProgressBar.test.tsx.snap
- packages/styleUtils/layout/flexbox/components/Flex.tsx
- packages/styleUtils/layout/flexbox/components/FlexItem.tsx
These changes will help eliminate some React errors
> Add `tag` prop to Flex/FlexItem + update markup in ProgressBar

- packages/index.ts
- packages/pageheader/components/PageHeaderBody.tsx
- packages/pageheader/index.ts
- packages/pageheader/stories/PageHeader.stories.tsx
Closes D2IQ-62146
Check out the "PageHeader > with PageHeaderBody " story.
> D2IQ-62146: adds PageHeaderBody component for consistent spacing in the PageHeader

- packages/design-tokens/README.md
- packages/design-tokens/scripts/transforms.js
Read the updated docs and comment if anything is missing or unclear
> Design token documentation

- package-lock.json
- package.json
> Update react as peer dependency

- README.md
used chore instead of fix in the last PR, triggering a release with this change
> Design guidelines are not WIP anymore

- package.json
attempt to correct the broken builds by using npx
> fix: broken build step

- .releaserc
- package-lock.json
- package.json
Upgrades semantic-release by two major versions, thus had to change the
releaserc config based on breaking changes. We'll also need to make sure
we're using LTS node version but Rodney and I couldn't come to a
decision about whether to introduce a node-version or nvmrc file.
> chore: update semantic-release version

- package-lock.json
- package.json
- packages/expandable/components/Expandable.tsx
- packages/expandable/stories/Expandable.stories.tsx
- packages/expandable/tests/Expandable.test.tsx
- packages/expandable/tests/__snapshots__/Expandable.test.tsx.snap
This dependency was producing console errors in development. Deprecate
its usage but maintain parity by using state within the expandable
component.
> fix: errors from react-toggled

- Jenkinsfile
try to run the validation steps in parallel. Also, remove the duplicate command to build storybook that's only needed for master builds
> chore: parallelize jenkins

- packages/dropdownMenu/components/DropdownMenu.tsx
- packages/dropdownMenu/components/DropdownSection.tsx
- packages/dropdownMenu/stories/Dropdown.stories.tsx
- packages/dropdownMenu/tests/__snapshots__/DropdownMenu.test.tsx.snap
- packages/tablev2/__snapshots__/tablev2.test.tsx.snap
Closes D2IQ-79942
This will allow us to set the commonly used actions to the bottom of our Workspace Picker in Kommander so they may be easily accessed with smaller dropdown heights. See https://jira.d2iq.com/browse/D2IQ-79944 
The light gradient is meant to help the user understand they are able to scroll. I wanted to use a lighter gradient since we can think of this sticky section above the other section and to improve the UX. 
A darker shadow appears off here due to our "global light source". Other elements that have shadows on our page will have the shadow appear more so on the bottom right for consistency (as the global light source is from above as it is on many applications). 
The footer will be one section that is sticky to the bottom of the dropdown menu. This section is meant to …
> feat: add sticky section functionality to dropdown

- Dockerfile
Update for docker to fix an error that showed up in Jenkins. Thank you @clintonmedbery for helping to troubleshoot.
> fix for docker build

- packages/modal/components/DialogModal.tsx
- packages/modal/stories/Modal.stories.tsx
- packages/modal/stories/helpers/ModalStoryContainer.tsx
- packages/modal/tests/__snapshots__/Modal.test.tsx.snap
Closes D2IQ-80933
Icon will be inserted to the left of the title, you can customize the icon size, color, and type. 
Note: I am not updating the story here to Controls, as there will be an update coming out soon on Storybook 6.4 that reforms the way to write CSF, will include these updates in the ui-kit chores ticket for updating the stories and controls. This is a rather large story that will have some more complex Controls to add and would be best to be separated out anyway.
> Optional Icons added to DialogModal title

- package-lock.json
- package.json
This is to align with the improvement to Kommander UI for suggested node/npm versions. 
- [] If any new components were added, there are exported from `packages/index.ts`
> Set suggested node/npm version in package.lock engines

- package-lock.json
- package.json
> fix: old npm version set in devDependencies

- packages/avatar/stories/avatar.stories.tsx
- packages/badge/components/ColorCodedBadge.tsx
- packages/badge/stories/badge.stories.tsx
- packages/badge/stories/colorcodedbadge.stories.tsx
- packages/chart/stories/LineChart.stories.tsx
- packages/donutChart/stories/DonutChart.stories.tsx
- packages/icon/stories/Icon.stories.tsx
- packages/progressbar/stories/ProgressBar.stories.tsx
Converted stories under the Graphic Elements and Charts folders from knobs to controls.
> controls to graphic elements and charts

- .github/workflows/ci.yml
- Jenkinsfile
> chore: update github actions

- packages/accordion/accordion.stories.tsx
- packages/breadcrumb/stories/Breadcrumb.stories.tsx
- packages/card/stories/Card.stories.tsx
- packages/card/stories/LinkCard.stories.tsx
- packages/inlineBorderedItems/components/InlineBorderedItems.tsx
- packages/inlineBorderedItems/stories/inlineBorderedItems.stories.tsx
- packages/link/stories/link.stories.tsx
- packages/pagination/Pagination.tsx
- packages/pagination/pagination.stories.tsx
- packages/styleUtils/layout/container/stories/Container.stories.tsx
- packages/styleUtils/layout/flexbox/components/Flex.tsx
- packages/styleUtils/layout/flexbox/stories/flex.stories.tsx
- packages/styleUtils/layout/flexbox/stories/flexItem.stories.tsx
- packages/styleUtils/layout/gridList/stories/GridList.stories.tsx
- packages/styleUtils/layout/stack/components/Stack.tsx
- packages/styleUtils/layout/stack/stories/stack.stories.tsx
- packages/tabs/stories/Tabs.stories.tsx
Converted stories under Navigation and Layout.
> add controls for navigation and layout

- .github/workflows/ci.yml
Created by following the outline here -> https://github.com/marketplace/actions/action-for-semantic-release
May be difficult to test as this is run when merging into master.
> chore: github action for semantic release

- packages/codesnippet/stories/CodeSnippet.stories.tsx
- packages/storybookHelpers/controlContants.ts
- packages/styleUtils/layout/stack/stories/stack.stories.tsx
- packages/styleUtils/modifiers/stories/BorderedBox.stories.tsx
- packages/styleUtils/modifiers/stories/Box.stories.tsx
- packages/styleUtils/modifiers/stories/SpacingBox.stories.tsx
- packages/styleUtils/typography/stories/headingText.stories.tsx
- packages/styleUtils/typography/stories/text.stories.tsx
Suggestions for changes/improvements to typography controls. Also includes the addition of a `controlConstants.ts` file to store reusable consts for the stories. 
**Changes of note:**
- Usage of `defaultValue` has been removed from the `argTypes`, and included in the args for the individual stories because it's being depreciated in Storybook 7.0
- I've exclude controls from certain stories where they were irrelevant or caused issues with other necessary controls. For instance:
- `vertAlignChildren` has been removed from the `DisplayInline` story because once you choose an option for that control it changes the display to `flex` and doesn't allow it to be changed back to `inline` or any other option. Also, the `vertAlignChildren` is irrelevant to the `DisplayInline` story anyway, as you …
> refactor: typography controls updates

- packages/card/components/Card.tsx
- packages/card/stories/Card.stories.tsx
- packages/card/style.ts
> feat: add card header for images

- CONTRIBUTING.md
- README.md
- package.json
- packages/icons/README.md
- packages/progressbar/README.md
- packages/styleUtils/layout/container/README.md
- packages/themes/README.md
Updates to the docs include copy edits, typos fixed, and wording that is more straightforward and clear.
Included updated markdown practices. 
References to DC/OS have been updated to D2iQ. 
Added the banner image to the readme. 
With these changes README.md will look similar to this:
> docs: update docs to reference d2iq and copy edits

- package-lock.json
- package.json
Kommander UI has recently transitioned to Cypress v9. 
Run `npm run test:integration` and the check should pass.
> chore: update cypress to latest v9

- packages/icons/src/icon-product/management-cluster.svg
The JIRA will be closed with the addition of this icon into the UI.
> feat: management cluster workspace product icon

- .storybook/docs/index.ts
- .storybook/docs/stories/Typography.stories.mdx
- .storybook/main.js
> docs: typography documentation

- packages/themes/stories/UIKitThemeProvider.stories.tsx
- packages/uiKitProvider/stories/UIKitProvider.stories.tsx
> fix: address Typescript errors in UIKitThemeProvider stories

- .github/workflows/ci.yml
> ci: include main in github actions

- packages/fullscreenView/components/FullscreenView.tsx
- packages/fullscreenView/stories/fullscreenView.stories.tsx
- packages/fullscreenView/style.ts
- packages/fullscreenView/tests/__snapshots__/fullscreenView.test.tsx.snap
- packages/modal/tests/__snapshots__/Modal.test.tsx.snap
This change should allow for banners on fullscreen view pages and modals. 
Additionally, the style changes may help to resolve the double scrollbar issue discovered in the UI.
> feat: fullscreenview banner component

- packages/dropdownable/components/Dropdownable.tsx
You would need to build rebuild `ui-kit` and manually copy the `dist` folder to `kommander`, I do it like this from `ui-kit`:
```bash
npm run dist && \
rm -rf ~/projects/work/kommander-ui/kommander/frontend/node_modules/@dcos/ui-kit/dist/packages && \
cp -r dist/packages ~/projects/work/kommander-ui/kommander/frontend/node_modules/@dcos/ui-kit/dist/
```
Make sure to update the paths to yours.
http://localhost:1234/workspace/kommander-workspace/access-control/roles/new and select a resource type.
I can not see any difference without the `getFlipModifier` applied, anybody knows in which situation we need it?
> D2IQ-87203: react-popper console errors

- packages/fullscreenView/components/FullscreenView.tsx
Exporting the `FullscreenViewProps` type so it can be used in kommander-ui for a custom component
> refactor: export FullscreenViewProps type

- package.json
- tsconfig.json
Run `npm i`.
Run `npm run dev`.
Make some changes and see if they appear.
https://github.com/gilamran/tsc-watch
> chore: added dev watch to ui-kit

- packages/typeahead/stories/Typeahead.stories.tsx
> chore: reintroduce multiselect typeahead story

- package-lock.json
- package.json
- packages/icons/scripts/build.js
* Closes D2IQ-88825
* Run `npm run dist` and copy the dist output into `kommander-ui` or link the package and see the icons.
> D2IQ-88825: update svgo

- packages/avatar/README.md
- packages/avatar/components/Avatar.tsx
- packages/avatar/stories/avatar.stories.tsx
- packages/avatar/style.ts
- packages/avatar/tests/__snapshots__/avatar.test.tsx.snap
- packages/clicktocopybutton/tests/__snapshots__/ClickToCopyButton.test.tsx.snap
- packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
- packages/icon/README.md
- packages/icon/components/Icon.tsx
Beginning the removal of React.FC and prep for React 18 and DS changes + general cleanup.
> refactor: avatar and icon types, props, and docs

- .github/PULL_REQUEST_TEMPLATE.md
Updates for our PR template. Aligning these changes with what we have for DKP with a few modifications related to this project.
> refactor: pull request template updates

- .github/workflows/chromatic.yml
@nataliepina and I found some changes in chromatic. The tool is awesome but we need some accountability here.
Trying to add some reporting for Chromatic. If you see it here it worked 😂
> feat: added chromatic reporting to PR

- packages/breadcrumb/components/Breadcrumb.tsx
- packages/breadcrumb/tests/Breadcrumb.test.tsx
- packages/breadcrumb/tests/__snapshots__/Breadcrumb.test.tsx.snap
- packages/card/components/ButtonCard.tsx
- packages/card/components/Card.tsx
- packages/card/components/LinkCard.tsx
- packages/card/stories/ButtonCard.stories.tsx
- packages/card/tests/ButtonCard.test.tsx
- packages/card/tests/Card.test.tsx
- packages/card/tests/LinkCard.test.tsx
- packages/card/tests/__snapshots__/ButtonCard.test.tsx.snap
- packages/card/tests/__snapshots__/Card.test.tsx.snap
- packages/card/tests/__snapshots__/LinkCard.test.tsx.snap
- packages/toggleBox/tests/ToggleBox.test.tsx
- packages/toggleBox/tests/ToggleBoxGroup.test.tsx
- packages/toggleBox/tests/__snapshots__/ToggleBox.test.tsx.snap
- packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap
swapping out class components for functions and also removing as much enzyme as I can. Using react-test-renderer where possible for snapshots.
Looks like the key components we'll want to validate against the existing storybook are:
*breadcrumb
*card
*buttoncard
*linkcard
*ToggleBox
> refactor: card components and breadcrumb

- package-lock.json
- package.json
- packages/accordion/__snapshots__/accordion.test.tsx.snap
- packages/badge/tests/__snapshots__/colorCodedBadge.test.tsx.snap
- packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap
- packages/popover/components/Popover.tsx
- packages/popover/components/PopoverListItem.tsx
- packages/popover/components/PopoverListItemIcon.tsx
- packages/tablev2/__snapshots__/tablev2.test.tsx.snap
- packages/textInput/components/TextInput.tsx
- packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
Closes D2IQ-90920
Updated Typescript to latest. Had to fix some TS related issues. Made some comments on those and made two commits as one is for updating snapshots.
- https://jira.d2iq.com/browse/D2IQ-90920
Really just click around and make sure things still work. The element with the biggest changes was dropdown menu.
> chore: update typescript

- packages/clicktocopybutton/tests/__snapshots__/ClickToCopyButton.test.tsx.snap
- packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
- packages/pageheader/components/PageHeader.tsx
- packages/pageheader/components/PageHeaderBody.tsx
- packages/tablev2/__snapshots__/tablev2.test.tsx.snap
- packages/tooltip/components/TooltipContent.tsx
- packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
refactoring tooltip and pageheader components to functions.
Regression test Tooltip and PageHeader stories
> refactor: tooltip and pageheader

- packages/infobox/components/InfoBox.tsx
- packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap
Converted the infobox component to a function component.
Converted the class component `infobox` into a function component.
#779 
Testing should be the same as before.
Nope :)
No visual changes.
> refactor: infobox component

- .github/workflows/ci.yml
While working on the code checks GitHub actions for DKP UI, I noticed that these checks could use some updates as well. Updates include bumps from v2 to v3. Formatting changes. The semantic version has been set to match the updated version - 19. 
Checks and tests pass ✅
> ci: update code checks and formatting

- packages/toggleBox/components/ToggleBoxGroup.tsx
- packages/toggleBox/stories/helpers/ToggleBoxGroupStoryHelper.tsx
- Changes ToggleBoxGroup from a class component to a function component
- Changes ToggleBoxGroupStoryHelper from a class component to a function component
Closes #788 
Testing can be done via storybook and the available unit tests.
No trade-offs noted.
No visual changes.
> Refactor ToggleBoxGroup Component

- packages/radioInput/__snapshots__/radioInput.test.tsx.snap
- packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap
- packages/shared/components/FormFieldWrapper.tsx
- packages/textInput/tests/__snapshots__/TextInput.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithButtons.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithIcon.test.tsx.snap
- packages/textarea/tests/__snapshots__/Textarea.test.tsx.snap
- packages/toggleInput/tests/__snapshots__/ToggleInput.test.tsx.snap
- packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap
Refactors FormFieldWrapper to a functional component.
fixes #787
- #787 
No changes to the UI
N/A
N/A - No Changes to the UI
> refactor: convert FormFieldWrapper to FC

- packages/tabs/README.md
- packages/tabs/components/TabItem.tsx
- Refactored the TabItem component to a function component. 
- Updated documentation for Tabs to give an example with a function component. 
Visual regression test on Storybook.
> refactor: update tabs docs and tabitem to fc

- packages/toggleBox/components/ToggleBox.tsx
- packages/toggleWrapper/components/ToggleWrapper.tsx
- packages/toggleWrapper/tests/__snapshots__/ToggleWrapper.test.tsx.snap
Refactor ToggleWrapper from a class component to a function component
https://github.com/dcos-labs/ui-kit/issues/796
Testing can be done via storybook and by running unit tests.
None
Not needed.
> refactor: turn ToggleWrapper into a function component

- packages/infobox/stories/InfoBox.stories.tsx
I've realized that we do not have a story for the `InfoBox` component.
I went back to an older branch and checked some past PRs to check if it was removed accidentally at some point and it appears that it was never created.
> docs: story for infobox component

- README.md
Updated the docs to include info about baseElement.
https://mesosphere.slack.com/archives/CQZ44D4SG/p1665679500919569
> docs: added information about baseelement

- packages/button/tests/ButtonBase.test.tsx
- packages/clicktocopybutton/tests/ClickToCopyButton.test.tsx
- packages/clicktocopybutton/tests/__snapshots__/ClickToCopyButton.test.tsx.snap
- packages/formStructure/tests/__snapshots__/fieldGroup.test.tsx.snap
- packages/formStructure/tests/__snapshots__/formStructure.test.tsx.snap
- packages/formStructure/tests/fieldGroup.test.tsx
- packages/formStructure/tests/formStructure.test.tsx
- packages/formStructure/tests/formSubSection.test.tsx
- packages/fullscreenView/tests/__snapshots__/fullscreenView.test.tsx.snap
- packages/fullscreenView/tests/fullscreenView.test.tsx
- packages/infobox/tests/InfoBox.test.tsx
- packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap
- packages/radioInput/__snapshots__/radioInput.test.tsx.snap
- packages/radioInput/radioInput.test.tsx
- packages/styleUtils/layout/container/tests/Container.test.tsx
- packages/styleUtils/layout/container/tests/__snapshots__/Container.test.tsx.snap
- packages/styleUtils/layout/gridList/tests/GridList.test.tsx
- packages/styleUtils/layout/gridList/tests/__snapshots__/GridList.test.tsx.snap
- packages/styleUtils/layout/stack/tests/__snapshots__/stack.test.tsx.snap
- packages/styleUtils/layout/stack/tests/stack.test.tsx
- packages/styleUtils/typography/tests/__snapshots__/typographyComponents.test.tsx.snap
- packages/styleUtils/typography/tests/typographyComponents.test.tsx
- packages/tabs/tests/Tabs.test.tsx
- packages/tabs/tests/__snapshots__/Tabs.test.tsx.snap
- packages/toggleBox/tests/ToggleBox.test.tsx
- packages/toggleInput/tests/ToggleInput.test.tsx
- packages/toggleInput/tests/__snapshots__/ToggleInput.test.tsx.snap
- packages/toggleWrapper/tests/ToggleWrapper.test.tsx
- packages/toggleWrapper/tests/__snapshots__/ToggleWrapper.test.tsx.snap
Migrating to react testing library
A batch of another set of test migrations so that it is easier to review. 
These include some event firing 🔥 
Leveling up my understanding of RTL best practices as I go.
> refactor: more refactoring away enzyme to rtl

- packages/toggleBox/stories/ToggleBox.stories.tsx
- packages/toggleBox/stories/helpers/ToggleBoxStoryHelper.tsx
Updates to improve the functionality of the ToggleBox story. Converted ToggleBoxStoryHelper to a function component.
Regression test for the ToggleBox story.
> refactor: togglebox story

- packages/button/components/ButtonBase.tsx
- packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
- packages/modal/tests/__snapshots__/Modal.test.tsx.snap
Refactored the `ButtonBase` from a class component to a function component. 
Visual regression testing for buttons, the button used for the modal, and the dropdownable.
> refactor: buttonbase from class to fc

- packages/formStructure/components/FieldList.tsx
- packages/formStructure/tests/__snapshots__/fieldList.test.tsx.snap
- packages/formStructure/tests/fieldList.test.tsx
- Refactors fieldList tests from enzyme to react-testing-library
- Closes #841 
- `npm run test`
- N/A
- N/A
> refactor: fieldList tests

- packages/selectInput/tests/SelectInput.test.tsx
- packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap
- Refactors selectInput tests from enzyme to react-testing-library
- Closes #805 
- `npm run test`
- N/A
- N/A
> refactor: selectInput tests

- packages/shared/styles/styleUtils/modifiers/modifierUtils.ts
This is based on an action item that came up in a Design System meeting with Nick. During his research, it was mentioned by a few of the UI team members that there was somewhat of a lack of clarity around the modifierUtils file. 
I've added a few comments to help with the understanding and to help future developers when they encounter this file. 
It was hard to find out why it was added by following the git history. Most of the related PRs did not have additional details on this file. 
Read it over and let me know if there are any additions or clarifications I should make.
> docs: comments to clarify modifierUtils.ts file

- packages/pagination/Pagination.tsx
- packages/pagination/__snapshots__/pagination.test.tsx.snap
- packages/pagination/pagination.test.tsx
- packages/promo/__snapshots__/promos.test.tsx.snap
- packages/promo/components/PromoContent.tsx
- packages/promo/promos.test.tsx
- packages/segmentedControl/tests/SegmentedControl.test.tsx
- packages/segmentedControl/tests/__snapshots__/SegmentedControl.test.tsx.snap
- Refactor test cases for Promo component from enzym to react-testing-library
- Refactor test cases for Pagination component from enzym to react-testing-library
- Closes #842 
- N/A
- N/A
- N/A
> refactor: convert enzym tests to react-testing-library-tests

- packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap
- packages/textInput/tests/TextInput.test.tsx
- packages/textInput/tests/TextInputWithBadges.test.tsx
- packages/textInput/tests/TextInputWithButtons.test.tsx
- packages/textInput/tests/__snapshots__/TextInput.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithButtons.test.tsx.snap
- packages/textInput/tests/__snapshots__/TextInputWithIcon.test.tsx.snap
- packages/textarea/tests/Textarea.test.tsx
- packages/textarea/tests/__snapshots__/Textarea.test.tsx.snap
- packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
- packages/utilities/label.tsx
- Migrates TextInput test cases from enzyme to react testing library
- Migrates TextInputWithButtons test cases from enzyme to react testing library
- Migrates Textarea test cases from enzyme to react testing library
- Migrates TextInputWithBadges test cases from enzyme to react testing library
- Closes #853 
- `npm run test`
- N/A
- N/A
> refactor: textInput tests

- packages/expandable/tests/Expandable.test.tsx
- packages/expandable/tests/__snapshots__/Expandable.test.tsx.snap
- Migrates test cases for Expandable component from Enzyme to react testing library
- Closes #861 
- `npm run test`
- N/A
- N/A
> Refactor testcases expandable

- packages/toaster/components/Toaster.tsx
- packages/toaster/stories/Toaster.stories.tsx
- packages/toaster/tests/Toaster.test.tsx
Some of these tests were testing internal component state. Opted instead to try and use visual cues that would result from such a state. This will make refactoring the component much easier.
> test: toaster tests with RTL

- packages/pageheader/components/PageHeader.tsx
- packages/pageheader/stories/PageHeader.stories.tsx
Changes TLDR;
- new component properties
- improved stories
These changes allow for a custom `className` and `dataCy` prop to be passed into the component. This can help to set a container on the PageHeader.
I've included some refactoring and improvements to the PageHeader stories. Adding comments around the types will improve the documentation under the Docs tab under Description in the props table. 
The best way to test this is with `npm link` and a custom className. 
With the changes to the stories, it defaulted set values and users cannot enter custom breadCrumbElements or actions. However, because these are arrays it is already hard with Storybook and IMO it's better if these are hard set instead of breaking when a user enters an object or array that storybook cannot process.
> PageHeader new custom properties

- package-lock.json
- package.json
- packages/accordion/components/AccordionItemTitleInteractive.tsx
- packages/badge/tests/__snapshots__/badge.test.tsx.snap
- packages/badge/tests/badge.test.tsx
- packages/card/tests/ButtonCard.test.tsx
- packages/configurationmap/tests/HashMap.test.tsx
- packages/configurationmap/tests/__snapshots__/HashMap.test.tsx.snap
- packages/donutChart/tests/DonutChart.test.tsx
- packages/donutChart/tests/__snapshots__/DonutChart.test.tsx.snap
- packages/dropdownMenu/components/DropdownMenu.tsx
- packages/expandable/tests/Expandable.test.tsx
- packages/formStructure/components/FieldListColumn.tsx
- packages/popover/tests/Popover.test.tsx
- packages/selectInput/tests/SelectInput.test.tsx
- packages/tablev2/tablev2.test.tsx
- packages/tabs/components/Tabs.tsx
- packages/tabs/tests/__snapshots__/Tabs.test.tsx.snap
- packages/toggleBox/components/ToggleBoxGroup.tsx
- packages/toggleContent/tests/ToggleContent.test.tsx
- packages/toggleWrapper/components/ToggleWrapper.tsx
- packages/typeahead/tests/Typeahead.test.tsx
- packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
includes test and type updates to support react 18
Closes D2IQ-92806
In order to support React 18 there are some changes that we'll be reliant on. 
Required changes included:
- There is a peer dependency error that will break CI if we do not update react-tabs, which then included some type updates for the Tabs component. 
- There were many locations where types for children had to be updated.
- Test updates were required. Use of `.click()` from react-test-renderer had to be refactored to use fireEvent from testing-library/react instead. I found locations using `create` from react-test-renderer that were broken and I aligned them with the rest of our testing updates using render queries from @testling-library/react. Updating both of these removed the use of react-test-renderer so it has …
> feat: react 18

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Added a PR template check for testing downstream changes. Updated the documentation around pre-release testing with npm-link.
> docs: steps and check for downstream testing

- .github/workflows/uffizzi-build.yml
- .github/workflows/uffizzi-preview.yml
- docker-compose.uffizzi.yml
This PR is a part of https://github.com/dcos-labs/ui-kit/issues/823 and helps demonstrate Uffizzi integration with **Ui-Kit**. 
This will help create preview environments on all of **Ui-Kit** Pull Requests and help contributors including the maintainers iterate faster on their PRs. 
I have created a PR over https://github.com/daramayis/f-ui-kit/pull/1#issuecomment-1302248763 to show what it looks like to have a preview environment deployed against your PR.
You can check out the preview over [here](https://pr-1-deployment-7137-f-ui-kit.app.uffizzi.com/) as well.
@waveywaves
>  feat: create environment for every PR using Uffizzi 

- packages/tabs/components/Tabs.tsx
> fix: use react-id-generator

- packages/tabs/components/Tabs.tsx
- packages/tabs/stories/Tabs.stories.tsx
> fix: use index as key to be not newly generated all the time

- .github/CODEOWNERS
- .storybook/docs/components/WelcomeCards.tsx
- README.md
- design-guidelines/form-ux.md
- package.json
- packages/design-tokens/README.md
- packages/pageheader/README.md
Update to reflect the repo org move.
> chore: rename old dcos things

- README.md
- package-lock.json
- package.json
- packages/themes/README.md
BREAKING CHANGE:
The package name has changed from @dcos/ui-kit to @d2iq/ui-kit
Closes D2IQ-90647
I've set this to a hold merge until we can create a package for this in the npm registry.
> feat: @d2iq/ui-kit package name

- .github/workflows/uffizzi-build.yml
- .github/workflows/uffizzi-preview.yml
> fix: ubuntu-latest issues with uffizzi

- packages/formStructure/components/FieldGroup.tsx
- packages/formStructure/components/FieldList.tsx
- packages/formStructure/components/FormMessage.tsx
- packages/formStructure/components/FormSection.tsx
- packages/formStructure/components/FormSectionBody.tsx
- packages/formStructure/components/FormSectionFooter.tsx
- packages/formStructure/components/FormSectionHeader.tsx
- packages/formStructure/components/FormSubSection.tsx
- packages/formStructure/components/FormTitle.tsx
- packages/formStructure/tests/__snapshots__/fieldGroup.test.tsx.snap
- packages/messagePanel/tests/__snapshots__/messagePanel.test.tsx.snap
- packages/messagePanel/tests/__snapshots__/messagePanelWithGraphic.test.tsx.snap
- packages/promo/__snapshots__/promos.test.tsx.snap
- packages/segmentedControl/components/SegmentedControl.tsx
- packages/segmentedControl/components/SegmentedControlButton.tsx
- packages/selectInput/components/SelectInput.tsx
- packages/slideToggle/components/SlideToggle.tsx
- packages/styleUtils/layout/flexbox/components/Flex.tsx
- packages/styleUtils/layout/flexbox/components/FlexItem.tsx
- packages/tablev2/__snapshots__/tablev2.test.tsx.snap
- packages/textarea/components/Textarea.tsx
- packages/toggleBox/components/ToggleBox.tsx
- packages/toggleBox/components/ToggleBoxGroup.tsx
- packages/toggleInput/components/ToggleInput.tsx
- packages/toggleInputList/components/ToggleInputList.tsx
- packages/typeahead/components/Typeahead.tsx
- Add className prop to components in the Form category
- Update snapshot tests
Note: The changes in this pull request are independent to pull request #912. So both PRs can be reviewed in any order.
https://github.com/d2iq/ui-kit/issues/893
View Components on Storybook
> feat: add optional className prop to Form category

- packages/avatar/components/Avatar.tsx
- packages/badge/components/ColorCodedBadge.tsx
- packages/badge/components/badge.tsx
- packages/badge/components/badgeButton.tsx
- packages/button/components/ButtonBase.tsx
- packages/card/components/ButtonCard.tsx
- packages/card/components/Card.tsx
- packages/formStructure/tests/__snapshots__/fieldGroup.test.tsx.snap
- packages/icon/components/Icon.tsx
- packages/inlineBorderedItems/components/InlineBorderedItems.tsx
- packages/messagePanel/tests/__snapshots__/messagePanel.test.tsx.snap
- packages/messagePanel/tests/__snapshots__/messagePanelWithGraphic.test.tsx.snap
- packages/promo/__snapshots__/promos.test.tsx.snap
- packages/styleUtils/layout/flexbox/components/Flex.tsx
- packages/styleUtils/layout/flexbox/components/FlexItem.tsx
- packages/tablev2/__snapshots__/tablev2.test.tsx.snap
- Add className prop to components in the Graphic Elements, Actions, and Layout categories
- Update snapshot tests
Note: The changes in this pull request are independent to pull request https://github.com/d2iq/ui-kit/pull/913. So both PRs can be reviewed in any order.
#893 
View Components on Storybook
> feat: add optional className props

- .github/workflows/storybook-tests.yml
- .storybook/docs/components/WelcomeBanner.tsx
- .storybook/main.js
- .storybook/webpack.config.js
- package-lock.json
- package.json
- webpack/webpack.base.js
This upgrades UI Kit to Webpack 5. 
- https://jira.d2iq.com/browse/D2IQ-96026 
Really just click around and make sure it works. Bonus points for using `npm link` or copying the dist to kommander ui and testing things.
Should be none.
> chore: upgrade ui kit to webpack 5

- package-lock.json
- package.json
Major version bump for babel-loader
Updated babel-loader version from 8.2.5 to 9.1.2
https://github.com/d2iq/ui-kit/issues/941
Storybook and run tests
> build: update babel-loader to version - 9.1.2

- package-lock.json
- package.json
Major version bump for wait-on
Updated wait-on version from 6.0.1 to 7.0.1
https://github.com/d2iq/ui-kit/issues/943
Storybook and run tests
> build: update wait-on to version - 7.0.1

- package-lock.json
- package.json
Major version bump for downshift
Updated downshift version from 6.1.12 to 7.3.2
https://github.com/d2iq/ui-kit/issues/942
Storybook and run tests
> build: update downshift to version - 7.3.2

- .github/workflows/uffizzi-build.yml
- .github/workflows/uffizzi-preview.yml
This PR updates Uffizzi Workflows to:
- track the most recent published version of Uffizzi reusable action
- add a fix for special characters in the PR event
Tested locally by creating a test PR
> Update Uffizzi Workflows

- packages/button/README.md
- packages/button/components/ButtonBase.tsx
- packages/button/components/WarningButton.tsx
- packages/button/components/WarningDropdownButton.tsx
- packages/button/index.ts
- packages/button/stories/DefaultButton.stories.tsx
- packages/button/stories/DropdownButton.stories.tsx
- packages/button/style.ts
- packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
- packages/index.ts
This introduces new button styles to handle warning messaging.
Closes D2IQ-96852
⚠️  
Introducing:
`WarningButton` and `WarningDropdownButton`
> feat: warningbutton and warningdropdownbutton

- packages/appChrome/README.md
- packages/avatar/README.md
- packages/badge/README.md
- packages/breadcrumb/README.md
- packages/button/README.md
- packages/card/README.md
- packages/checkboxInput/README.md
- packages/clickable/README.md
- packages/clicktocopybutton/README.md
- packages/codesnippet/README.md
- packages/configurationmap/README.md
- packages/donutChart/README.md
- packages/dropdownMenu/README.md
- packages/dropdownable/README.md
- packages/expandable/README.md
- packages/formStructure/README.md
- packages/fullscreenView/README.md
- packages/icon/README.md
- packages/icons/README.md
- packages/infobox/README.md
- packages/inlineBorderedItems/README.md
- packages/link/README.md
- packages/list/README.md
- packages/loadingIndicator/README.md
- packages/messagePanel/README.md
- packages/modal/README.md
Closes D2IQ-97207
This is the first set of work to update component documentation files. 
Our component readme files are important to understanding additional information about our components such as how they work, quirks, best practices, and other information that helps inform us how to appropriately utilize them.
Outdated documentation is never good. These files haven't had a proper review in over 3 years. So to keep things fresh and reviewed. I've gone through and provided additional context, copy edits, and more. A few components were lacking any documentation so I added it.
I've batched these changes into 2 parts to make it easier to review these changes.
> docs: reviewed and updated component docs

- .github/workflows/release.yml
We did not build ui-kit before publishing it using `semantic-release` after we've separated out release in it's own workflow. 
This is most  likely why all these modules were missing because they never got into the release.
If you look into the `semantic-release` step in these logs you can see a lot of missing `dist/packages` files:
before extracting into it's own workflow: https://github.com/d2iq/ui-kit/actions/runs/4959492707/jobs/8873669645
after extracting into it's own workflow: https://github.com/d2iq/ui-kit/actions/runs/5248683318/jobs/9480498718
https://d2iq.atlassian.net/browse/D2IQ-97741
Wait for a new release and update ui-kit in kommander-ui
> ci: run `dist` before release to have the needed files available

- packages/tablev2/TooltipHeaderCell.tsx
- packages/tablev2/__snapshots__/tablev2.test.tsx.snap
- packages/tooltip/README.md
- packages/tooltip/components/TooltipIcon.tsx
- packages/tooltip/index.ts
- packages/tooltip/stories/Tooltip.stories.tsx
This introduces a TooltipIcon component that can be used as a trigger. It will help with consistent tooltip icon usage.
There are new docs that outline how to use the icons.
Closes D2IQ-97013
While testing out some Tooltip updates in the UI, I realized we are using the Icon component in many places to repeatedly with the same values as a Tooltip trigger. I first thought to create a reusable atom component for this in the UI, which made me come to the realization that this should live in UI Kit with it being many times throughout the app.
Creating a component for this will also help to define the intended use and alleviate some of the consistency issues we've encountered with this icon. 
In the UI, we discovered there has been an inconsistent use of icon color for the tooltip icons. The …
> feat: tooltipicon component

- packages/index.ts
There is another location where components need to be exported for them to be used from the library.
> fix: export the tooltipicon component for use

- package-lock.json
- package.json
It was regarding updation of @testing-library/jest-dom to version 6
> build: Updated @testing-library/jest-dom to version 6

- packages/appChrome/style.ts
- packages/button/components/ButtonBase.tsx
- packages/shared/styles/color.ts
- packages/shared/styles/normalize.ts
- packages/shared/styles/styleUtils/typography/color.ts
- packages/tablev2/tablev2.test.tsx
- packages/themes/stories/UIKitThemeProvider.stories.tsx
This removes TODO messages that are stale,
do not have a related task, or not necessary.
Prior to these changes we have around 16 TODO messages throughout the application. 
I've noticed that many of these are pretty old or don't have the proper context anymore. 
Some of these we will probably not get around to doing as well, therefore I think we can safely remove them. 
This will reduce the TODO maintenance burden and improve the professionalism of the code. 
Over time, codebases evolve, and priorities change. Old TODOs may no longer be relevant to the current state of the project. Removing them keeps the codebase clean and ensures that we can focus on addressing current tasks and issues. Accumulating a large number of unresolved TODOs can clutter the code. 
I have addressed the remaining …
> chore: todo message cleanup

- .storybook/docs/colors.ts
- .storybook/docs/stories/Colors.stories.mdx
Improved the organization and style of the color docs. Created a separate file for color doc configurations.
I checked on the storybook Colors addon to see if there were any major updates recently.
With this work, I did a bunch of little improvements all over such as improved headers.
I decided to provide a better color system and organization. The configuration I wanted here became huge and I definitely felt that warranted it's own file, which cleans up the Colors.stories.tsx file SO much.
It's also hard to have things formatted correctly in MDX files depending on what the content is so moving it out helped with formatting. 
One more important improvement here is that you have the name of the color token closer to the value it represents. 
I think this makes it easier to compare colors …
> docs: storybook color documentation updates

- .storybook/docs/stories/Typography.stories.mdx
I took some time to review the storybook docs on Typography along with some competitive research.
I think we had a pretty good structure on this one, I mainly did some clean up on this file. 
Updated things to have more of a MDX flavor with the markdown headers and then JSX chunks of the text examples. I changed the code example to lorem impsum too 🤷🏻‍♀️ 
Also I tried out adding a section of some common text colors to use. 
I worked on this one in tandem with the work to update Colors and I tried to make sure there was consistency between the two such as the heading text. 
Test out the Typography docs. 
**before**
**after**
> docs: updated typography documentation

- .github/dependabot.yml
- .github/workflows/dependabot-automations.yml
These changes add a config file for dependabot.
Dependabot helps to create routine dependency updates.
This introduces depnedabot for UI Kit! 
Merging this will trigger the dependabot updates.
> build: dependabot configuration

- .github/workflows/dependabot-automations.yml
> ci: dependabot automations fix

- .github/dependabot.yml
Let dependabot update gh-actions
> ci: configure dependabot to update github actions
