d2iq/ui-kit

package-lock.json
package.json

`npm` is adding the `node_modules/.bin/` directory to the path so there is no need to use it in the
scripts section from the `package.json`.

chore(package): remove node modules binary directory from scripts

---

components/badge/badge.tsx

This PR improves the `badge` component to only accept specific props that way developers will be warned if some unexpected prop is passed.
**before**:
**after**:

feat: specify badge properties

---

scripts/commit-msg

This fixes the issue where a commit is not created if the commit msg is not fulfilling the
convetion. Which means that the commit lint is telling you to run `git commit --amend` to change the
message which means that the changes are appended to the previous commit. Also the message entered
before is lost, which means if someone has entered a rather long commit message that work would have
been lost.

chore(commit-msg): fix commit msg hook

---

packages/badge/components/badgeButton.tsx
packages/badge/tests/__snapshots__/badgeButton.test.tsx.snap
packages/badge/tests/badgeButton.test.tsx

<details><summary><strong>fix(buttonbadge): change form button to button role</strong></summary><hr/>
This changes the the element from a button to a span and is adding the `role="button"` attribute to
the element.
</details>
---
Commit:
e846642ba5ccedefe464b1989207383586d9cbb5

Change to badgeButton to have a role

---

packages/badge/style.ts
packages/badge/tests/__snapshots__/badge.test.tsx.snap
packages/badge/tests/__snapshots__/badgeButton.test.tsx.snap
packages/shared/stories/color.stories.tsx
packages/shared/styles/color.ts
tsconfig.json

This adds all the color values from our UI kit. 
They are named so we are using the same names across systems (Sketch in our case).
Not all color shades will be necessary but the key is we shouldn't use any colors that aren't defined here.
To test the table start storybook with 
```bash
npm start
```
As soon as this starts visit [http://localhost:6006/?selectedKind=Colors&selectedStory=Color](http://localhost:6006/?selectedKind=Colors&selectedStory=Color%20table&full=0&addons=1&stories=1&panelRight=1&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
You should see the table.

Add color values from UI kit

---

packages/utilities/components/compose.ts
packages/utilities/components/max.ts
packages/utilities/components/min.ts
packages/utilities/components/percentage.ts
packages/utilities/index.ts
packages/utilities/tests/compose.test.ts
packages/utilities/tests/max.test.ts
packages/utilities/tests/min.test.ts
packages/utilities/tests/percentage.test.ts

<details><summary><strong>feat(utilities): add min helper function</strong></summary><hr/>
This will provide a curried function to calculate the min value of two parameters. This should be
replaced by ramda as soon as their types have been fixed.
Close DCOS-38496
</details>
---
Commit:
77beb493cad778db3e6df1f1a584f9069025cea2
<details><summary><strong>feat(utilities): this adds a max helper function</strong></summary><hr/>
This provides a max helper function for the users. The function is curried and should be replaced by
ramda as soon as their types are fixed.
Close DCOS-38639
</details>
---
Commit:
ae22a28a0fd218de47c3bb55c2087e428e5afcdd
<details><summary><strong>feat(utilities): add percentage helper</strong></summary><hr/>
This provides the user wiht a curried helper function. The …

DCOS-38496, DCOS-38639, DCOS-38640: Table helper functions for calculating width

---

packages/index.ts
packages/table/components/Cell.tsx
packages/table/components/HeaderCell.tsx
packages/table/components/TextCell.tsx
packages/table/index.ts
packages/table/stories/Table.stories.tsx
packages/table/tests/Cell.test.tsx
packages/table/tests/__snapshots__/Cell.test.tsx.snap

<details><summary><strong>feat(table): add cell component</strong></summary><hr/>
This adds a cell component which provides basic styling for cell content.
</details>
---
Commit:
b65ccc17854c6692e626ecbf54e1eec9a58b234e
<details><summary><strong>feat(table): add header cell component</strong></summary><hr/>
This adds a HeaderCell Component which provides basic styling for table headers.
</details>
---
Commit:
3b71b4b43a318f6aa152dd21f2f89e537cf1a9fb
<details><summary><strong>feat(table): add text cell component</strong></summary><hr/>
This adds a TextCell component which provides basic styling for text cells. Specifically
`text-transform: ellipsis;`
</details>
---
Commit:
74e3dd14acd2a07dd9f9c577c989071637b713d5
<details><summary><strong>docs(table): add cell …

DCOS-37578: Add Cell component helpers

---

tsconfig.json

*Solution*
Paired with @Fabs to find a fix for the dist issue.
Explicitly target emotion types to fix module import in ts, from:
```ts
declare const _default: import("../../../../../../../Users/fabs/ship/ui-kit/node_modules/create-emotion-styled/types/react").StyledOtherComponent<{}, import("../../../../../../../Users/fabs/ship/ui-kit/node_modules/create-emotion-styled/types/common").StyledOtherProps<React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>, any, React.Ref<any>>, any>;
```
to:
```ts
/// <reference path="../../../../node_modules/emotion/types/index.d.ts" />
/// <reference types="react" />
declare const _default: import("react").StyledOtherComponent<{}, React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>, any>;
export default …
```

fix: styled types path not found

---

packages/table/components/TextCell.tsx
packages/table/tests/__snapshots__/Cell.test.tsx.snap

<details><summary><strong>fix(table): fix text cell white space wrap</strong></summary><hr/>
This fixes white space wrap to no wrap so that the text is getting correctly shortend.
</details>
---
Commit:
6583318f02ba4301ccf4c97bad380787406742a0

Fix TextCell to not wrap

---

packages/table/components/HeaderCell.tsx
packages/table/tests/__snapshots__/Cell.test.tsx.snap

This `uppercase` css property is removed in order to make only first letter in headers capital.
related jira: https://jira.mesosphere.com/browse/DCOS-39677

DCOS-39677: Capitalize only first letter in table header

---

packages/table/components/Table.tsx
packages/table/style.ts
packages/table/tests/__snapshots__/Table.test.tsx.snap

Jira ticket: https://jira.mesosphere.com/browse/DCOS-39675
Before (in Chrome):
After (in Chrome):
I chose to do this by hiding the scrollbar with vendor-specific CSS on both grids
**Pros:**
- User can scroll when cursor is in either of the right grids
- Vendor-specific CSS will be ignored by browsers who don't support these rules, so no surprise bugs
**Cons:**
- Only works for IE/Edge and webkit browsers
I also looked at using `overflow: hidden` on top-left grid, browser-specific for bottom-left. This would still let the top-left grid scroll, but it would never show a scrollbar, so only the bottom scrollbar would appear in browsers that don't give you a way to style/hide it's scrollbars.
**Pros:**
- Firefox and other browsers that are incompatible with the vendor-specific styles will only …

DCOS-39675: Hide scrollbars in Table grids

---

packages/table/components/Table.tsx
packages/table/style.ts

Before:
After (the hover shadow is _very_ hard to see in after the uploaded gif has been compressed, but it's there):

DCOS-40355: add hover style for Table rows

---

packages/toggleContent/components/toggleContent.tsx
packages/toggleContent/tests/__snapshots__/toggleContent.test.tsx.snap
packages/toggleContent/tests/toggleContent.test.tsx

The click event was completing when a user highlighted text and released the click
Before:
After:

DCOS-41098: ToggleContent no toggle when text highlighted

---

packages/toggleContent/style.ts
packages/toggleContent/tests/__snapshots__/toggleContent.test.tsx.snap

DCOS-41116: add dashed underline on ToggleContent text

---

package-lock.json
package.json
packages/badge/components/badge.tsx
packages/badge/components/badgeButton.tsx
packages/clickable/components/clickable.tsx
packages/shared/styles/color.ts
packages/shared/styles/typography.ts
packages/table/components/Cell.tsx
packages/table/components/Column.tsx
packages/table/components/NumberCell.tsx
packages/table/components/SortableHeaderCell.tsx
packages/table/components/Table.tsx
packages/table/stories/Table.stories.tsx
packages/toggleContent/components/toggleContent.tsx

Remove "I" prefix from interface types, and upgraded to the latest [@dcos/tslint-config](https://github.com/dcos-labs/tslint-config)

DCOS-39139: rename types to conform to our latest tslint config

---

package-lock.json
package.json

<p>This Pull Request updates devDependency <code>tslint-plugin-prettier</code> (<a href="https://renovatebot.com/gh/ikatyang/tslint-plugin-prettier">source</a>) from <code>v1.3.0</code> to <code>v2.0.0</code></p>
<p><details><br />
<summary>Release Notes</summary></p>
<h3 id="v200httpsgithubcomikatyangtslint-plugin-prettierblobmasterchangelogmd8203200httpsgithubcomikatyangtslint-plugin-prettiercomparev130v200-2018-09-16"><a href="https://renovatebot.com/gh/ikatyang/tslint-plugin-prettier/blob/master/CHANGELOG.md#&#8203;200httpsgithubcomikatyangtslint-plugin-prettiercomparev130v200-2018-09-16"><code>v2.0.0</code></a></h3>
<p><a href="https://renovatebot.com/gh/ikatyang/tslint-plugin-prettier/compare/v1.3.0…v2.0.0">Compare Source</a></p>
<h5 id="bug-fixes">Bug Fixes</h5>
<ul>
<li>specify …

chore(deps): update dependency tslint-plugin-prettier to v2

---

renovate.json

Expanding the practice of auto merging dev deps updates in `dcos-labs` repos.

Enable renovate autoMerge for dev deps

---

packages/table/README.md
packages/table/components/Column.tsx
packages/table/components/Table.tsx
packages/table/stories/Table.stories.tsx

Only moved over things that are currently in the ui-kit. Will port over more once we have more table components built out in the ui-kit. 
[Design System Docs](https://docs.google.com/document/d/1HiT0YTZe930DdSukKapahfzMG9Dc-pEKIjFUBuVeyw0/edit#heading=h.earj3o607tlu)
Closes DCOS-41268

DCOS-41268: port table docs from google docs

---

package-lock.json
package.json
packages/infobox/components/InfoBox.tsx
packages/infobox/style.ts
packages/shared/styles/breakpoints.ts
packages/shared/styles/global.ts
packages/shared/styles/spacing.ts
packages/shared/styles/styleUtils/index.ts
packages/shared/styles/styleUtils/layout/flexbox.ts
packages/shared/styles/styleUtils/modifiers/margin.ts
packages/shared/styles/styleUtils/modifiers/modifierUtils.ts
packages/shared/styles/styleUtils/modifiers/padding.ts
packages/shared/styles/styleUtils/typography/color.ts
packages/toaster/README.md
packages/toaster/components/Toast.tsx
packages/toaster/components/Toaster.tsx
packages/toaster/index.ts
packages/toaster/stories/Toaster.stories.tsx
packages/toaster/style.ts
packages/toaster/tests/Toast.test.tsx
packages/toaster/tests/Toaster.test.tsx
packages/toaster/tests/__snapshots__/Toast.test.tsx.snap

This should work as-is, but we can probably follow-up to make `Toaster` stateless by storing `toasts` data in the datalayer and adding GraphQL mutations for adding and removing toasts

DCOS-40966: added components to handle toast notifications

---

packages/index.ts

Forgot to export InfoBox and Toast components in `packages/index.ts` 😳

fix: export notification components

---

package-lock.json
package.json
packages/toaster/components/Toaster.tsx
packages/toaster/style.ts
packages/toaster/tests/__snapshots__/Toast.test.tsx.snap

I had to replace the `react-pose` dependency with `react-transition-group` because I hadn't realized `react-pose` requires React 16.
I tested this by running `npm run dist` and then manually replacing `dcos-ui/node_modules/ui-kit/dist` with `dist` directory generated in ui-kit
**This needs to merge before I can submit a PR for [DCOS-40871](https://jira.mesosphere.com/browse/DCOS-40871)**

fix: React 15 compatibility

---

.storybook/config.js
packages/shared/styles/global.ts
packages/toaster/components/Toaster.tsx
packages/toaster/style.ts
packages/toaster/tests/__snapshots__/Toast.test.tsx.snap

Injecting global element styles was overriding some CNVS styles that we want in dcos-ui.

fix: do not export global element reset styles

---

package.json

This fixes the release process of ui kit the build storybook step was failing unfortunately because the design tokens were not created.

fix(storybook): fix storybook build to create design tokens

---

packages/appChrome/components/AppChrome.tsx
packages/appChrome/style.ts
packages/appChrome/tests/__snapshots__/AppChrome.test.tsx.snap
packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap

Before, the Sidebar height would only be the height of it's children. Now, it will always be the height of it's container.
I also removed the gutter between the Sidebar and the main content area
This was causing issues for implementing the sidebar in the Learning Platform
Before:
After:

fix(AppChrome): make AppChrome always fill it's container's height

---

package.json

The deploy step of master was broken because of the design tokens which were not build. The problem was that the module we are using to deploy storybook does just build storybook and not run `build:storybook`.

fix(storybook): build design tokens pre deploy

---

packages/button/style.ts
packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap

Lily and I discussed potential issues with aligning the text of a secondary button with other text on the page or in a modal.
We decided to change the secondary button to have no padding and a different `:focus` style.

DCOS-46141: remove padding from secondary button

---

package.json
packages/modal/stories/Modal.stories.tsx
packages/modal/style.ts
packages/modal/tests/__snapshots__/Modal.test.tsx.snap

- Fixed text input focus in "custom focused element" story
- Changed `react-delegate-component` to be a pinned release
- Added a little padding between checkbox input and button in 
- Added `aria-haspopup` to buttons that open the modal*
*this change wasn't requested, but Storybook stories should set good examples

Address post-merge modal feedback

---

package-lock.json
package.json

It's unclear whether this will fix an underlying issue or not, but it would be good not to bundle two versions of react nonetheless.

fix: Convert React to peer dependency

---

packages/table/components/Table.tsx

I tested this in the Nodes table in dcos-ui, and in Storybook by creating a story with changing values
To test in dcos-ui:
1. run `npm run dist`
2. copy `dist/packages/table` to `dcos-ui/node_modules/@dcos/ui-kit/dist/packages/table`

fix: dynamic cell widths update with content changes

---

packages/modal/components/DialogModal.tsx
packages/modal/components/DialogModalWithFooter.tsx
packages/modal/components/FullscreenModal.tsx
packages/modal/components/ModalBase.tsx
packages/table/components/Column.tsx
packages/table/components/SortableHeaderCell.tsx
packages/textInput/components/TextInput.tsx
uiKitStory.ts

This will help with translation using lingui.
In other cases, string | ReactNode was simplified to ReactNode because that type already includes string.

fix: Props should allow ReactNode in certain cases 

---

packages/table/components/Column.tsx
packages/table/components/Table.tsx
packages/table/stories/Table.stories.tsx
packages/table/tests/Table.test.tsx
packages/table/tests/__snapshots__/Table.test.tsx.snap

Adding the `growToFill` prop to a column allows that column to grow until the table fills it's parent. `maxWidth`, `minWidth`, and `width` props will still work in conjunction with this even though I can't think of a realistic use case for combining those with `growToFill` ¯\_(ツ)_/¯
In this example, the "Role" and "City" columns have `growToFill`:

DCOS_OSS-4364: allow column width to fill available space

---

packages/appChrome/components/Sidebar.tsx
packages/appChrome/components/SidebarItem.tsx

It is too strict and we don't do any operations with `children` prop. We don't map it, nor filter, neither we enforce a specific type of a child.
Other alternative would be to use type from React that cover all possible types of a child.
Without this change this code https://github.com/dcos-labs/ui-shell-app/blob/19be4a16844a4dc67d1a2b30e707a373f27f7cae/src/components/AppSidebar.tsx#L20 fails with
```
[tsl] ERROR in /src/components/AppSidebar.tsx(30,11)
TS2322: Type '{ children: Element[]; isOpen: boolean; }' is not assignable to type 'Readonly<SidebarProps>'.
Types of property 'children' are incompatible.
Type 'Element[]' is not assignable to type 'string | ReactElement<HTMLElement>'.
Type 'Element[]' is not assignable to type 'ReactElement<HTMLElement>'.
Property 'type' is missing in …
```

Remove children prop type from Sidebar

---

packages/shared/styles/styleUtils/index.ts
packages/shared/styles/styleUtils/modifiers/vAlignChildren.ts
packages/table/README.md
packages/table/components/CheckboxTable.tsx
packages/table/components/Table.tsx
packages/table/stories/Table.stories.tsx
packages/table/style.ts
packages/table/tests/__snapshots__/Cell.test.tsx.snap
packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
packages/table/tests/__snapshots__/Table.test.tsx.snap

Before this, table rows could only be the default height, 35px
Table rows that are 60px high:

DCOS-46403: allow table row heights other than default

---

packages/appChrome/tests/AppChrome.test.tsx
packages/design-tokens/scripts/transforms.js
packages/shared/styles/styleUtils/modifiers/modifierUtils.ts
packages/toaster/components/Toast.tsx

no need to `break` after a `return`!
also fixes a type error saying that React has no default export.

remove unreachable code

---

packages/toaster/components/Toast.tsx
packages/toaster/components/Toaster.tsx
packages/toaster/stories/Toaster.stories.tsx
packages/toaster/tests/Toast.test.tsx
packages/toaster/tests/Toaster.test.tsx

Refactored Toaster to always trust it's children as the source of truth
for which toasts should be displayed. This requires the app using
toaster to keep and accurate list of toasts and handle removing toasts
from that list whenever onDismiss callback is invoked.
Updated `autodismiss` code to also ensure onDismiss callback is called.

DCOS-49609 refactor(Toaster): children as source-of-truth

---

packages/tooltip/components/Tooltip.tsx
packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap

This resolves a console error when "on click outside" triggers for tooltips. However, there is a bigger underlying problem here that I don't fully understand and is also hard to google: The props defined in each component appear to allow undefined values when they in fact not allowed. This should have been a typescript error

fix(ui): required prop missing from Dropdownable

---

packages/tooltip/components/Tooltip.tsx
packages/tooltip/tests/Tooltip.test.tsx
packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap

I tested a Protoss PR where we were using a Tooltip inside of a table and noticed hovering the Tooltip would only work sometimes. This was likely due to the cell re-rendering when on hover to add the row hover styles.
Changing the Tooltip event handler from `onMouseEnter` to `onMouseOver` appears to fix this issue. I tested both in Storybook and in Protoss
Before:
After:
[Protoss before](https://cl.ly/48efc03a1e6b)
[Protoss after](https://cl.ly/79a21202566c)

Tooltip improvement: use mouseOver instead of mouseEnter

---

packages/table/components/Table.tsx
packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
packages/table/tests/__snapshots__/Table.test.tsx.snap

We noticed in Protoss that the table cells were rewriting the DOM nodes for table cells instead of changing the attributes of the table cell nodes. This was causing images to flicker on state change and components like `Tooltip` inside the table to unnecessarily do expensive re-renders.
Before:
After:

Table cell perf fix: only re-render classname for cells

---

packages/dropdownable/components/Dropdownable.tsx
packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap

There are a few more examples of this in Sidebar and Headerbar, but this in particular is much easier to fix and is affecting protoss performance

fix: don't create styled component in render function

---

packages/tooltip/components/Tooltip.tsx
packages/tooltip/tests/Tooltip.test.tsx

It would be nice to know whenever the tooltip is closed, in case I want to reset its contents.
Example
"Copy to Clipboard" > "Copied!" > "Copy to Clipboard"

feat(ui): onClose callback on tooltip

---

package-lock.json
packages/table/components/CheckboxTable.tsx
packages/table/components/Column.tsx
packages/table/components/Table.tsx
packages/table/stories/Table.stories.tsx
packages/table/tests/CheckboxTable.test.tsx
packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
packages/table/tests/__snapshots__/Table.test.tsx.snap

This removes the Table's ability to measure all cells and calculate column widths based on content sizing. We're removing this because that functionality was making the Table's performance very poor in dcos-ui.
I investigated alternatives that would allow us to keep the content-based column width sizing, but could not find a way to do it that didn't seriously hurt Table performance.

DCOS-50093: table perf - remove content-based column width sizing

---

packages/table/components/Table.tsx
packages/table/stories/Table.stories.tsx
packages/table/style.ts
packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
packages/table/tests/__snapshots__/Table.test.tsx.snap

Before, table column widths were being calculated based on the width of the area the table filled. However, on Windows and Linux, a scrollbar is displayed on the right and causes a horizontal scroll.
Now, we measure the scrollbar width and factor that into the column width calculations.

DCOS-50412: account for scrollbars for Table col widths

---

package.json
packages/table/components/Table.tsx
packages/table/style.ts
packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
packages/table/tests/__snapshots__/Table.test.tsx.snap

For some reason, when the table is wrapped in a div, it will not be rendered by Cypress' browser until you explicitly set the correct height on that wrapper div.
Using a `Fragment` instead of a DOM node will also fix this issue.

rm table wrapper div that breaks integration tests

---

Jenkinsfile
package.json
webpack/webpack.base.js

The last PR (https://github.com/dcos-labs/ui-kit/pull/325) to fix the Storybook deployment had a few issues:
- We weren't building before deploying, so there was no directory (`storybook_static`) to deploy
- Webpack 4 threw an error for using `UglifyJSPlugin` instead of `optimization.minimize`*
- Args were being passed to `storybook-to-ghpages` twice
This PR should _actually_ fix the issue. Thanks for being patient 🙏

fix(storybook): add build to deployment step

---

packages/dropdowMenu/components/DropdownMenuItem.tsx
packages/dropdowMenu/style.ts
packages/dropdowMenu/tests/__snapshots__/DropdownMenuItem.test.tsx.snap
packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap

If a menu item's text is one long string with no spaces, the background color would only extend to the width of the menu.
This seems like an unlikely scenario, but we discovered it by testing a Typeahead that could contain long ID strings.
Background has been changed to pink for demonstration purposes
Before:
After:

fix: extend DropdownMenuItem bg color with text

---

packages/index.ts
packages/legacy/README.md
packages/legacy/index.ts
packages/legacy/src/Tooltip/Tooltip.tsx
packages/legacy/src/Tooltip/style.ts
packages/legacy/src/Tooltip/tests/Tooltip.test.tsx
packages/legacy/src/Tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
packages/legacy/src/Util/DOMUtil.ts

This moves the legacy Tooltip component over from reactjs-components.
Once we port all components reactjs-components to ui-kit, dcos-ui can import legacy components from ui-kit and drop reactjs-components as a dependency.
1. In ui-kit, run `npm run dist`
2. Replace `dcos-ui/node_modules/@dcos/ui-kit/dist/packages/` with `ui-kit/dist/packages/`
3. Find a place in `dcos-ui` that uses a Tooltip imported from `reactjs-components` and replace the import with
```
import { Legacy } from "@dcos/ui-kit";
```
4. Replace `<Tooltip />` components with `<Legacy.Tooltip />`
5. Start dcos-ui
Check that `<Legacy.Tooltip />` looks and behaves like the `<Tooltip>` from reactjs-components
1. Import legacy components to a `*.stories.tsx` file:
```
import { Legacy } from "@dcos/ui-kit";
```
2. Add a story …

DCOS-54215: port Tooltip from reactjs-components

---

packages/pageheader/README.md
packages/pageheader/components/PageHeader.tsx
packages/pageheader/index.ts
packages/pageheader/stories/PageHeader.stories.tsx
packages/pageheader/style.ts
packages/pageheader/tests/PageHeader.test.tsx
packages/pageheader/tests/__snapshots__/PageHeader.test.tsx.snap

This adds a minimal implementation for a page header.
CLOSES DCOS-54461
Depends on #331

DCOS-54461 feat(pageheader): add minimal component implementation

---

packages/appChrome/stories/AppChrome.stories.tsx

`PlaceholderIcon` was deleted, so the stories would error when you tried to load stories that used it

Fix broken AppChrome stories

---

package-lock.json
package.json
packages/legacy/index.ts
packages/legacy/src/Dropdown/Dropdown.tsx
packages/legacy/src/Dropdown/DropdownListTrigger.tsx
packages/legacy/src/Dropdown/DropdownTrigger.tsx
packages/legacy/src/Dropdown/styles.ts
packages/legacy/src/Dropdown/tests/Dropdown.test.tsx
packages/legacy/src/Dropdown/tests/DropdownListTrigger-test.js
packages/legacy/src/Dropdown/tests/__snapshots__/Dropdown.test.tsx.snap
packages/legacy/src/Dropdown/tests/fixtures/MockDropdownList.ts

This moves the legacy Dropdown component over from reactjs-components.
Once we port all components reactjs-components to ui-kit, dcos-ui can import legacy components from ui-kit and drop reactjs-components as a dependency.
0. In `dcos-ui`, update ui-kit to the latest version (currently 3.8.0) and run `npm install`.
1. In ui-kit, run `npm run dist`
2. Replace `dcos-ui/node_modules/@dcos/ui-kit/dist/packages/` with `ui-kit/dist/packages/`
3. Find a place in `dcos-ui` that uses a Dropdown imported from `reactjs-components` and replace the import with
```
import { Legacy } from "@dcos/ui-kit";
```
4. Replace `<Dropdown />` components with `<Legacy.Dropdown />`
5. Start dcos-ui
Check that `<Legacy.Dropdown />` looks and behaves like the `<Dropdown>` from reactjs-components
1. Import legacy …

[spike] DCOS-54216: port Dropdown from reactjs-components

---

packages/shared/styles/styleUtils/layout/flexbox.ts
packages/styleUtils/layout/flexbox/components/Flex.tsx
packages/styleUtils/layout/flexbox/stories/flex.stories.tsx
packages/styleUtils/layout/flexbox/tests/__snapshots__/Flex.test.tsx.snap
packages/styleUtils/modifiers/components/Box.tsx
packages/styleUtils/modifiers/tests/__snapshots__/Box.test.tsx.snap
packages/styleUtils/typography/components/CaptionText.tsx
packages/styleUtils/typography/components/DangerText.tsx
packages/styleUtils/typography/components/HeadingText1.tsx
packages/styleUtils/typography/components/HeadingText2.tsx
packages/styleUtils/typography/components/HeadingText3.tsx
packages/styleUtils/typography/components/InteractiveText.tsx
packages/styleUtils/typography/components/MonospaceText.tsx
packages/styleUtils/typography/components/SmallText.tsx
packages/styleUtils/typography/components/SuccessText.tsx
packages/styleUtils/typography/components/Text.tsx
packages/styleUtils/typography/components/WarningText.tsx
packages/styleUtils/typography/tests/__snapshots__/typographyComponents.test.tsx.snap

While using the style utility components in Kommander, I noticed a few small things that could be improved. This PR:
- kills browser default margins on typography components
- typography elements' text alignment defaults to inherit
- Flex component can accept children that are null
- fixed an issue with responsive flex-direction styles
- doesn't set empty background-image rule for Box

Small tweaks to style utility components

---

packages/modal/components/DialogModalWithFooter.tsx

This changes the closeText prop to be optional on the DialogModalWithFooter component to cover the
rare case were we want to show a informational message.

feat(modal): change closeText to a optional prop on dialog with footer

---

packages/appChrome/stories/AppChrome.stories.tsx
packages/appChrome/style.ts
packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap

I found this issue when using a white background color for the Kommander sidebar.
You can test this by using the Knobs panel in the ["Sidebar Customizable w/ Knobs" story](http://localhost:6006/?path=/story/appchrome--sidebar-customizable-w-knobs) to change the Sidebar background color to white.
**Before:**
**After:**

Color selected Sidebar item text based on selected bg color

---

packages/appChrome/components/HeaderBar.tsx
packages/appChrome/components/SidebarItem.tsx
packages/appChrome/components/SidebarSection.tsx
packages/appChrome/stories/AppChrome.stories.tsx

This change is needed for the latest Kommander/Konvoy header bar designs - where the logo is at the top left with no padding.
This can be tested by choosing "none" from the padding-related select knobs in the Knobs panel

Allow AppChrome components' padding to be 0 via theming

---

packages/card/README.md
packages/card/components/Card.tsx
packages/card/stories/Card.stories.tsx
packages/card/style.ts
packages/card/tests/Card.test.tsx
packages/card/tests/__snapshots__/Card.test.tsx.snap
packages/shared/styles/styleUtils/index.ts
packages/shared/styles/styleUtils/modifiers/preserveAspectRatio.ts

These cards in Konvoy and Kommander are limited by a 4:5 aspect ratio, and I think we may end up using this again.

Add aspectRatio prop to Card

---

packages/card/components/Card.tsx
packages/card/stories/Card.stories.tsx
packages/card/tests/Card.test.tsx
packages/card/tests/__snapshots__/Card.test.tsx.snap

The designers wanted to be able to use padding inside the card component other than `spaceM` (16px)

DCOS-56472: Add paddingSize prop to Card

---

packages/appChrome/components/SidebarItem.tsx
packages/appChrome/components/SidebarSubMenu.tsx
packages/appChrome/components/SidebarSubMenuItem.tsx
packages/appChrome/stories/AppChrome.stories.tsx
packages/appChrome/style.ts
packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap
packages/appChrome/types/appChromeTheme.ts

This issue surface while I was implementing the latest designs for the Konvoy/Kommander AppChrome when the designers asked me to try a light grey background.
Note: the light grey sidebar background isn't showing in the GIF color space, but I think this still demonstrates the changes :)
**Before:**
**After (with a themed hover bg color):**

DCOS-56497: themable SidebarItem hover background color

---

packages/donutChart/components/DonutChart.tsx
packages/donutChart/tests/__snapshots__/DonutChart.test.tsx.snap

In a recent review of Kommander work, the design team requested two minor changes to the donut chart:
- A thinner stroke weight for the donut chart
- A lighter grey for the un-filled part of the chart
**Before:**
**After:**

DCOS-56473: Update DonutChart styles

---

packages/appChrome/components/AppChrome.tsx
packages/appChrome/tests/__snapshots__/AppChrome.test.tsx.snap
packages/card/style.ts
packages/card/tests/__snapshots__/Card.test.tsx.snap

card: inner div is set to 100% to match the card's height
appchrome: make the wrapper for the main content area 100% to avoid strange bug where bottom of the main content is cut off when the sidebar and main content area scroll together

fix: tweaks to card and appchrome layout

---

packages/button/style.ts
packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
packages/tooltip/stories/Tooltip.stories.tsx

1. In the "default" Tooltip story, replace the `trigger` prop with:
```
trigger={<PrimaryButton disabled={true}>Hover me</PrimaryButton>}
```
2. Hover over the button and then off the button
The tooltip should disappear when your cursor leaves the button
**Before:**
**After:**

fix: hides tooltip when mouse leaves disabled button

---

package.json

This was causing an issue with releases because the compiled Typescript would get blown away when CI ran the 'Build Storybook' step.
- `npm run dist`
- builds the distribution where designTokens.ts gets compiled with tsc
- `npm run build:storybook`
- removes the design-token directories via clean:design-tokens
- rebuilds icons and design-tokens, but does not run tsc
- `npx run semantic-release`
- publishes to npm without compiled JS design tokens

Fix Typescript design-tokens distribution

---

packages/table/components/Cell.tsx
packages/table/tests/__snapshots__/Cell.test.tsx.snap
packages/table/tests/__snapshots__/SortableHeaderCell.test.tsx.snap
packages/utilities/getReactChildrenText.ts
packages/utilities/tests/getReactChildrenText.test.tsx

We want to ensure that table cell text content is always accessible to the user, even when a cell is truncated.
This commit gives every Table cell DOM node a `title` attribute so users get a browser-native tooltip when hovering the cell.
This work was done to support [DCOS-39095](https://jira.mesosphere.com/browse/DCOS-39095) (see Jira comments for better context)

DCOS-39095: adds browser-native tooltip to all table cells

---

packages/styleUtils/layout/gridList/style.ts
packages/styleUtils/layout/gridList/tests/__snapshots__/GridList.test.tsx.snap

fix: prevent gridlist cell content from overflowing

---

packages/appChrome/tests/__snapshots__/AppChrome.test.tsx.snap
packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap
packages/breadcrumb/tests/__snapshots__/Breadcrumb.test.tsx.snap
packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
packages/checkboxInput/tests/__snapshots__/CheckboxInput.test.tsx.snap
packages/configurationmap/tests/__snapshots__/ConfigurationMap.test.tsx.snap
packages/configurationmap/tests/__snapshots__/HashMap.test.tsx.snap
packages/expandable/tests/__snapshots__/Expandable.test.tsx.snap
packages/modal/tests/__snapshots__/Modal.test.tsx.snap
packages/pageheader/tests/__snapshots__/PageHeader.test.tsx.snap
packages/shared/styles/styleUtils/layout/flexbox.ts
packages/styleUtils/layout/flexbox/components/Flex.tsx
packages/styleUtils/layout/flexbox/stories/flex.stories.tsx
packages/styleUtils/layout/flexbox/tests/__snapshots__/Flex.test.tsx.snap
packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
packages/table/tests/__snapshots__/Table.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInput.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInputWithIcon.test.tsx.snap
packages/toggleInput/tests/__snapshots__/ToggleInput.test.tsx.snap
packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap
packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap

When setting a `gutterSize` and setting a `direction` prop to "column" or "column-reverse", the padding on the FlexItem remained on the left instead of moving to the top.
Before:
After:

[spike] DCOS-56720: correct which side gutterSize appears for column direction

---

packages/dropdownable/components/Dropdownable.tsx
packages/segmentedControl/README.md
packages/segmentedControl/components/SegmentedControlButton.tsx
packages/segmentedControl/stories/SegmentedControl.stories.tsx
packages/segmentedControl/style.ts
packages/tooltip/components/Tooltip.tsx
packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap

1. Go to the SegmentedControl "with tooltip content" story
2. Confirm that Tooltips appear when hovering the segment buttons

DCOS-58216: add tooltipContent prop to SegmentedControlButton

---

packages/badge/components/badge.tsx
packages/badge/style.ts
packages/selectInput/components/SelectInput.tsx
packages/shared/styles/formStyles.ts
packages/textInput/README.md
packages/textInput/components/TextInputWithBadges.tsx
packages/textInput/components/TextInputWithIcon.tsx
packages/textInput/index.ts
packages/textInput/stories/TextInputWithBadges.stories.tsx
packages/textInput/stories/helpers/TextInputWithBadgesStoryHelper.tsx
packages/textInput/stories/helpers/TextInputWithBadgesTypeaheadStoryHelper.tsx
packages/textInput/style.ts
packages/textInput/tests/TextInputWithBadges.test.tsx
packages/textInput/tests/__snapshots__/TextInput.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
packages/typeahead/components/Typeahead.tsx
packages/typeahead/tests/Typeahead.test.tsx
packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap

You should be able to add badges by hitting "Enter" after you type some value into the input
You should be able to add badges using the Typeahead variants
You can't add duplicates
**Default:**
**Pre-filled:**
**w/ a Typeahead:**
---
Some small things I'd like to address before merging, but probably aren't blockers:

DCOS-57982: component for rendering badges in a text input

---

packages/pageheader/components/PageHeader.tsx
packages/pageheader/components/PageHeaderTabs.tsx
packages/pageheader/style.ts
packages/pageheader/tests/__snapshots__/PageHeader.test.tsx.snap
packages/tabs/components/Tabs.tsx
packages/tabs/tests/__snapshots__/Tabs.test.tsx.snap

This issue came up during Kommander beta development
Tables grow to the height of their parent. This is a problem when you have a Table that's inside of Tabs because the tab panels get the height of their children.

Make it easier to render a Table in a tab panel

---

packages/avatar/style.ts
packages/avatar/tests/__snapshots__/avatar.test.tsx.snap

This adds a **very** subtle light grey border around avatars in the case that the image being used has a white background.
Here's what I put in `src` to test this and take screenshots: ```data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOMAAADeCAMAAAD4tEcNAAAAA1BMVEX///+nxBvIAAAASElEQVR4nO3BMQEAAADCoPVPbQZ/oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+A8W4AAH7AbJ4AAAAAElFTkSuQmCC```
**Before:**
**After:**

Add subtle border around Avatars

---

packages/dropdownMenu/README.md
packages/dropdownMenu/components/DropdownMenu.tsx
packages/dropdownMenu/components/DropdownMenuItem.tsx
packages/dropdownMenu/stories/Dropdown.stories.tsx
packages/dropdownMenu/tests/DropdownMenu.test.tsx
packages/popover/components/PopoverListItem.tsx
packages/popover/tests/__snapshots__/PopoverListItem.test.tsx.snap
packages/typeahead/components/Typeahead.tsx
packages/typeahead/stories/Typeahead.stories.tsx
packages/typeahead/stories/helpers/itemMocks.tsx
packages/typeahead/tests/Typeahead.test.tsx

This was done in support of [DCOS-60200](https://jira.mesosphere.com/browse/DCOS-60200).
I also took care of this for the Typeahead dropdown while I was making changes

DCOS-60200: support for disabled dropdown menu items

---

package-lock.json
package.json
packages/table/components/Table.tsx

When react-draggable's Draggable component unmounts, it causes text inputs to lose focus. These changes add a workaround for this problem: https://github.com/mzabriskie/react-draggable/issues/315
This bug was discovered while working on Kommander. Internal D2iQ Slack thread here: https://mesosphere.slack.com/archives/CMAAP82G6/p1572061677078800

Fix for text inputs losing focus when table w/ resizable column unmounts

---

packages/shared/styles/styleUtils/modifiers/modifierUtils.ts
packages/styleUtils/modifiers/components/SpacingBox.tsx
packages/styleUtils/modifiers/stories/SpacingBox.stories.tsx
packages/styleUtils/modifiers/tests/SpacingBox.test.tsx
packages/styleUtils/modifiers/tests/__snapshots__/SpacingBox.test.tsx.snap

There was a case in Kommander where I needed spacing on all sides but the bottom, and I think we'll also have situations where we want one spacing value for the left and right sides,  but a different spacing value for the top and bottom sides.

DCOS-56745: allow SpacingBox to set spacing per side

---

packages/infobox/style.ts
packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap

Try putting a very long string with no whitespace into the infobox and make sure it doesn't flow outside of the box

DCOS-60921: improves handling of long unbroken strings in infobox

---

packages/table/style.ts
packages/table/tests/__snapshots__/SortableHeaderCell.test.tsx.snap

When sort direction is "ascending" the arrow should point up
Here is the fixed version:

fix: arrow direction / asc & desc

---

packages/textInput/components/TextInputWithBadges.tsx
packages/textInput/stories/TextInputWithBadges.stories.tsx
packages/textInput/tests/TextInputWithBadges.test.tsx
packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap

- Ensure a badge with the input value is added to the input when blurring the input
- A badge should not be added if the `addBadgeOnBlur` prop is set to `false`

TextInputWithBadges update: adds input value as badge on blur

---

packages/icon/components/Icon.tsx
packages/loadingIndicator/components/InlineLoadingIndicator.tsx
packages/loadingIndicator/components/SectionLoadingIndicator.tsx
packages/loadingIndicator/tests/__snapshots__/loadingIndicator.test.tsx.snap

Forgot to add `data-cy` attributes

Make it easier to select loading indicator elements with Cypress

---

packages/formStructure/components/FieldGroup.tsx
packages/formStructure/components/FieldList.tsx
packages/formStructure/stories/fieldList.stories.tsx
packages/formStructure/tests/fieldList.test.tsx

This fixes two issues:
- Keys were not being properly set on children of the FieldList 
- If the value of a FieldListColumn's child input was the value of an object property who's key was literally the string "key", the field would lose focus each time the value of the input changed
- In each object in the `mockItems` array, change the key "name" to "key"
- In the "interactive example" story, update the first `FieldListColumn`'s `pathToValueProp` to "key"
- Open the "interactive example" story in Storybook
Ensure that the value of the input can be changed and doesn't lose focus whenever you type a new letter
**Before:**
**After:**

fix: changes the way keys are set on grouped fields (FieldList, FieldGroup)

---

package.json

npm frequently complains about the peerDependencies of ui-kit not being fulfilled as we (dcos-ui) use react `16.12.0`. is there any particular reason to have the restriction to `<16.9.0`?

fix: broaden version of react peerDeps

---

packages/formStructure/tests/__snapshots__/formStructure.test.tsx.snap
packages/infobox/components/InfoBox.tsx
packages/infobox/style.ts
packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap

Sometimes we use `InfoBoxInline` or `InfoBoxBanner` in a narrow part of the screen (like a small dialog modal), so we can't depend on media queries to handle wrapping the actions to their own line.
**Before:**
**After:**

Wrap InfoBox actions to a new line without media queries

---

packages/button/components/ButtonBase.tsx
packages/button/components/ResetButton.tsx
packages/configurationmap/tests/__snapshots__/ConfigurationMap.test.tsx.snap
packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
packages/emptyState/tests/__snapshots__/emptyState.test.tsx.snap
packages/emptyState/tests/__snapshots__/emptyStateWithGraphic.test.tsx.snap
packages/formStructure/tests/__snapshots__/fieldList.test.tsx.snap
packages/fullscreenView/tests/__snapshots__/fullscreenView.test.tsx.snap
packages/modal/tests/__snapshots__/Modal.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInputWithButtons.test.tsx.snap

These changes were made to accommodate buttons nested inside of a <form> element. Without the 'type' attribute set, buttons inside of a <form> element default to 'type=submit', which causes unwanted/premature form submissions. When kommander upgrades to a version of ui-kit that includes these changes, Jira ticket DCOS-62594 should be resolved.

Set button type attribute to "button" by default

---

packages/checkboxInput/components/CheckboxInput.tsx
packages/checkboxInput/stories/CheckboxInput.stories.tsx
packages/checkboxInput/tests/__snapshots__/CheckboxInput.test.tsx.snap
packages/shared/components/FormFieldWrapper.tsx
packages/shared/styles/formStyles.ts
packages/table/components/CheckboxTable.tsx
packages/table/tests/CheckboxTable.test.tsx
packages/table/tests/__snapshots__/CheckboxTable.test.tsx.snap
packages/toggleInput/components/ToggleInput.tsx
packages/toggleInputList/components/ToggleInputList.tsx
packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap

I asked the design team about this pattern:
They said clicking the hint text should not toggle the input. I made it possible to pass `hintContent` to an individual `CheckboxInput`, and automatically render the correct styling and functionality.
This might have been annoying to do manually in a consumer application, and prone to layout bugs if we changed the size of the toggle input.

CheckboxInput followup: added hint text to toggle input

---

packages/shared/styles/global.ts
packages/shared/styles/normalize.ts

DCOS-62619: globally style all anchor tags

---

packages/textInput/components/TextInputWithBadges.tsx
packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap

These changes prevent a form from being submitted when pressing the "Enter" key inside of a TextInputWithBadges input.

Don't submit a form when pressing enter inside of a TextInputWithBadges

---

packages/modal/components/ModalBase.tsx
packages/modal/style.ts
packages/modal/tests/__snapshots__/Modal.test.tsx.snap

When centering using positioning and transform, sometimes modal content would appear a little blurry on low-res screens.
See Jira.

DCOS-59641: use flexbox for centering to avoid subpixel blur

---

packages/appChrome/components/SidebarSubMenuItem.tsx

Closes [D2IQ-63790](https://jira.d2iq.com/browse/D2IQ-63790)

D2IQ-63790: darken the text color for sidebar submenu items on a light background

---

packages/tableView/components/TableViewBody.tsx

These changes are a workaround for a react-virtualized bug, but I can't track down what is causing a problem.
We noticed the issue in the create/edit role form in Kommander.

fix: TableBody minRows sets correct height

---

packages/icons/src/icon-product/cluster-attach-inverse.svg
packages/icons/src/icon-product/cluster-attach.svg
packages/icons/src/icon-product/file-yaml-inverse.svg
packages/icons/src/icon-product/file-yaml.svg
packages/icons/src/icon-product/global-inverse.svg
packages/icons/src/icon-product/global.svg

Adds product icons for representing:
- the global level of an organization's hierarchy
- attaching a cluster to a management cluster
- YAML files
Closes D2IQ-64258, D2IQ-64264, and D2IQ-64265

D2IQ-63606: add new icons used in Kommander

---

packages/button/components/ButtonBase.tsx
packages/button/stories/DefaultButton.stories.tsx

There are already plans to improve how we deal with links in ui-kit ([D2IQ-61570](https://jira.d2iq.com/browse/D2IQ-61570)), but I'm not sure when that ticket will get worked on. 
This is an issue that causes enough headaches that I think this quick fix makes sense.

Adds a prop to open button links in a new tab

---

packages/checkboxInput/components/CheckboxInput.tsx
packages/checkboxInput/tests/__snapshots__/CheckboxInput.test.tsx.snap
packages/toggleBox/tests/__snapshots__/ToggleBox.test.tsx.snap
packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap
packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap
packages/toggleWrapper/components/ToggleWrapper.tsx
packages/toggleWrapper/tests/__snapshots__/ToggleWrapper.test.tsx.snap

they most likely also appear during runtime.
there are 3 warnings left that need some more attention than just changing some
prop names. :/
👇 those are no more!

chore: remove some warnings that appear during jest

---

package-lock.json
package.json
packages/table/components/Table.tsx
packages/table/stories/helpers/ResizableTableOnResizeDemo.tsx

it seems overkill to have a big library for handling two places that need
immutable data.
this should trim down the size of the build a bit (like ~15kb gzipped on dcos-ui).

refactor: remove immutable

---

packages/toggleBox/tests/__snapshots__/ToggleBox.test.tsx.snap
packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap
packages/toggleWrapper/components/ToggleWrapper.tsx
packages/toggleWrapper/tests/__snapshots__/ToggleWrapper.test.tsx.snap

When this changed to an uncontrolled component, it prevented the ToggleBoxGroup component from calling `onChange` in an edge case: https://github.com/mesosphere/kommander/pull/1945#pullrequestreview-371033905

Change ToggleWrapper back to a controlled component

---

packages/appChrome/style.ts
packages/appChrome/tests/__snapshots__/Sidebar.test.tsx.snap

macOS users: to focus anchor tags in Firefox, you need to change a setting in System Preferences.
1. Go to System Preferences > Keyboard > Shortcuts
2. Toggle the radio button at the bottom to be "All controls"
Before:
After:

Hides SidebarSubMenuItem focus outline in Firefox

---

packages/table/components/Table.tsx

These changes fix an issue where the table would have space between the columns when adding or removing columns.

Recalculate Table column widths when column children change

---

packages/index.ts
packages/promo/README.md
packages/promo/__snapshots__/promos.test.tsx.snap
packages/promo/components/PromoBanner.tsx
packages/promo/components/PromoContent.tsx
packages/promo/components/PromoInline.tsx
packages/promo/index.ts
packages/promo/promos.test.tsx
packages/promo/stories/promoBanner.stories.tsx
packages/promo/stories/promoInline.stories.tsx
packages/promo/style.ts
packages/promo/types.ts

Navigate to the PromoInline and PromoBanner stories to make sure they look correct, and the documentation is useful and easy to follow.
Note: the top and bottom padding in PromoCard is intentionally smaller than what is in Kommander.

D2IQ-66278: adds PromoBanner, PromoInline, and PromoContent

---

packages/icons/src/icon-product/cd-inverse.svg
packages/icons/src/icon-product/cd.svg
packages/icons/src/icon-product/ci-inverse.svg
packages/icons/src/icon-product/ci.svg

D2IQ-66902
Confirm the icons are showing in Storybook, but it's safe to merge this without testing. 
Currently, the CI icon is the same as the CI/CD icon. The design team is planning on making an icon to represent CI/CD, so I didn't remove it.

feat(icons): adds product icons for CI and CD

---

packages/tablev2/Table.tsx

Without this change, if we try conditionally removing a column from the table, we get this:

chore: allow removing columns from table

---

packages/avatar/style.ts
packages/avatar/tests/__snapshots__/avatar.test.tsx.snap

These changes also include styles that show an outline around avatars so they are visible when they are on a background that is the same color
Closes D2IQ-68105
Layout quirks:
On top of the same background color:
Layout quirks:
On top of the same background color:

D2IQ-68105: removes styles that affect layout

---

packages/shared/styles/normalize.ts

Using Chrome version 83 or higher, confirm that our `Textarea` is set in a sans-serif font, not a monospace font.
I don't actually understand the reason Chrome added this default style. I'm just changing this because I know our design team will ask us to.
If any reviewers have a reason we shouldn't override the monospace font style, please let me know!
Before:
After:

feat(textarea): overrides monospace font-family in Chrome 83+

---

README.md
packages/modal/tests/__snapshots__/Modal.test.tsx.snap
packages/utilities/interactionMode.ts

With my last change, I introduced a state bug that I don't fully understand but it was manifest by stale classes showing up on buttons. Switching the argument order seems to fix it without state.
I added some docs for how to test without release. I was noticing the disabled state on the save button was broken on the policy modal in 4.9.0
n/a
n/a
n/a

interaction mode bug

---

packages/expandable/components/Expandable.tsx
packages/expandable/style.ts
packages/expandable/tests/__snapshots__/Expandable.test.tsx.snap
packages/index.ts

Closes D2IQ-69416
Confirm the triangle icon appears to the left of the text label

D2IQ-69416: moves Expandable's indicator icon to the left side

---

packages/expandable/components/Expandable.tsx

Added an optional `onChange` handler to the Expandable component so that
users can be notified when the Toggle is clicked and handle updates.

feat(Expandable): add onchange handler prop

---

packages/accordion/__snapshots__/accordion.test.tsx.snap
packages/accordion/style.ts

Closes D2IQ-70625
Go to the accordion stories (http://localhost:6006/?path=/story/navigation-accordion--default).
Confirm that accordion title and accordion panel content is separated by a border.
Before:
After:

D2IQ-70625: adds bottom border to accordion item titles

---

packages/textarea/components/Textarea.tsx
packages/textarea/stories/Textarea.stories.tsx

- See the new [hint text and error](http://localhost:6006/?path=/story/forms-textarea--hint-text-and-error) Textarea story and ensure you see both hint text and error message
Before
After

fix: ensure both hintcontent and errors are shown below Textarea

---

package-lock.json
package.json
packages/accordion/accordion.stories.tsx
packages/dropdownMenu/tests/__snapshots__/DropdownMenu.test.tsx.snap
packages/dropdownable/components/Dropdownable.tsx
packages/popover/components/PopoverBox.tsx

Try opening a dropdown menu powered by dropdownable (Typeahead, DropdownMenu) that has too many items to fit in the viewport.
The dropdown menu should be scrollable
Bonus: test this in Kommander using the workspace selection dropdown populated with a bunch of workspaces
https://share.getcloudapp.com/eDuBl7BJ

D2IQ-70983: constrain dimensions of dropdown element passed to Dropdownable to the dimensions of the viewport

---

packages/formStructure/tests/__snapshots__/fieldList.test.tsx.snap
packages/textInput/components/TextInput.tsx
packages/textInput/tests/__snapshots__/TextInput.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInputWithButtons.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInputWithIcon.test.tsx.snap
packages/textarea/components/Textarea.tsx
packages/textarea/stories/Textarea.stories.tsx
packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
packages/utilities/label.tsx

`TextInput` nicely provides us with the ability to specify a `tooltipContent`
and then displays an appropriate tooltip right besides the label above the
input.
`Textarea` now can do this too! :tada:
i first copied over all the parts but then decided to start a utility. 
so we extracted `getLabelContent` and `getTooltipContent` from `TextInput` and refactored those a bit. 
by now i feel that a next step could be to make that an `input`-utility and put even more
shared code there. but that's something for another PR. :)
also somehow some changes regarding our data-cy-classes emerged as i found those
way too noisy:
```diff
-    const dataCy = [
-      "textInput",
-      ...(appearance && appearance !== InputAppearance.Standard
-        ? [`textInput.${appearance}`]
-        : [])
- …
```

feat(Textarea): allow for `tooltipContent`

---

packages/icons/src/icon-system/spinner.svg

Confirm that `<Icon shape={SystemIcons.Spinner} color="red" />` renders a red spinner.

fix: enables SystemIcons.Spinner SVG to take a fill color

---

packages/formStructure/components/FieldList.tsx
packages/formStructure/components/FieldListAddButton.tsx
packages/formStructure/components/FieldListColumn.tsx
packages/formStructure/components/FieldListContext.tsx
packages/formStructure/stories/fieldList.stories.tsx
packages/formStructure/tests/fieldList.test.tsx

Closes D2IQ-68837
- Go to any FieldList story
- Tab through the last row and confirm a new row appears when you tab from the last input to the last close button
- Tab through the new row _without typing values in the inputs_ and confirm that a new row is not added when you tab from the last input to the last close button
I'm using `onKeyUp` and checking for the "Tab" key to add a new row. I tried a few approaches using onBlur and onFocus, but they felt even more hacky
https://share.getcloudapp.com/2Nuy9ZLX

D2IQ-68837: creates a new row in a fieldlist when tabbing off last input

---

packages/emptyState/components/EmptyState.tsx
packages/emptyState/stories/emptyState.stories.tsx
packages/emptyState/style.ts
packages/emptyState/tests/__snapshots__/emptyState.test.tsx.snap
packages/emptyState/tests/emptyState.test.tsx

1. Look at the new story to preview `appearance="error"`
2. Test the width update in Kommander:
- `npm run dist`, then copy result to `kommander/kommander/frontend/node_modules/@dcos/ui-kit/dist/`
- Look at some Kommander screens that show the `EmptyState` component
The EmptyState card width should max out at 450px unless there is a `CodeSnippet` inside - then the width should max out at the parent's width. Resizing the viewport to <450px should also resize the `EmptyState` card to a narrower width.
I'm not sure whether or not we'll add other variations to the `appearance` prop
Demo of width updates: https://share.getcloudapp.com/jkuZjGBo
`appearance="error"`

D2IQ-71117: EmptyState error appearance + width update

---

packages/configurationmap/components/ConfigurationMapLabel.tsx
packages/configurationmap/components/ConfigurationMapRow.tsx
packages/configurationmap/components/ConfigurationMapSection.tsx
packages/configurationmap/components/ConfigurationMapValue.tsx
packages/configurationmap/style.ts
packages/configurationmap/tests/ConfigurationMap.test.tsx
packages/configurationmap/tests/HashMap.test.tsx
packages/configurationmap/tests/__snapshots__/ConfigurationMap.test.tsx.snap
packages/configurationmap/tests/__snapshots__/HashMap.test.tsx.snap
packages/table_deprecated/components/Table.tsx
packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap

The styles broke with the emotion 10 upgrade, and I missed it because we weren't putting styles in the snapshots.
Confirm that ConfigurationMap components look right
Before:
After:

Fix ConfigurationMap styles

---

packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
packages/emptyState/tests/__snapshots__/emptyState.test.tsx.snap
packages/emptyState/tests/__snapshots__/emptyStateWithGraphic.test.tsx.snap
packages/expandable/tests/__snapshots__/Expandable.test.tsx.snap
packages/promo/__snapshots__/promos.test.tsx.snap
packages/shared/styles/styleUtils/layout/flexbox.ts
packages/styleUtils/layout/flexbox/stories/flex.stories.tsx
packages/styleUtils/layout/flexbox/tests/__snapshots__/Flex.test.tsx.snap
packages/tablev2/__snapshots__/tablev2.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap

Closes D2IQ-69910
Confirm there is no indentation of rows when `<Flex>` has `wrap="wrap"` and `gutterSize` props set.
Before:
After:

D2IQ-69910: eliminates indentation of wrapping FlexItems when Flex has gutterSize set

---

packages/index.ts
packages/pagination/Pagination.tsx
packages/pagination/PaginationContainer.tsx
packages/pagination/README.md
packages/pagination/__snapshots__/pagination.test.tsx.snap
packages/pagination/index.ts
packages/pagination/pagination.stories.tsx
packages/pagination/pagination.test.tsx
packages/pagination/style.ts
packages/pagination/usePageChange.ts
packages/textInput/components/TextInput.tsx

Closes D2IQ-72667
Play with the Pagination stories in Storybook and make sure they match up with the Invision mock.
Maybe we should create a "ControlledPagination" component so we don't have props that look too similar:
- `initialActivePage`(for uncontrolled) and `activePage` (for controlled)
- `initialPageLength` (for uncontrolled) and `pageLength` (for controlled)

D2IQ-72667: Pagination component

---

packages/formStructure/components/FieldListColumn.tsx

The FieldList and FieldListColumn components allow consumers to define any type of onChange handler for their field columns, and even allow configuring the `value` type via generic. Currently we are not able to fully take advantage of this `value` flexibility because the render props `onChange` handler assumes that the event will be an InputElement form event. To allow use with different types of inputs (like selects) and different types of form controls that don't use form events at all (like TextInputWithBadges), a second generic is added to the column definition.
Should work as usual

fix: add second generic to FieldListColumnProps definition

---

packages/icon/README.md
packages/icon/components/Icon.tsx
packages/icon/style.ts
packages/icon/tests/Icon.test.tsx
packages/icon/tests/__snapshots__/Icon.test.tsx.snap

Added a `block` flag to the Icon props to allow changing the svg from the
default `display: inline` to `display: block` this will allow an icon to
use `margin: auto` inside flex. This is useful when displaying an icon
next to text and we want them to be aligned.
I did not change the default since it would break the rendering for
other components.
I initially set `block` as a default prop set to false, but this then
broke every snapshot. Instead I just made it an optional prop.
Alternative to a block flag we could of made a display prop the defaults
to inline and can be set to any valid display CSS value. I'm not opposed
to this but didn't need it now.

feat: add block display override to icon

---

.storybook/preview.js

This change enables story source to show in storybook and fixes incorrect prop types tables.
- `npm start` and make sure you can see story source and that prop tables show correct props
- For some reason storybook-readme is wiping out the syntax highlighting on source blocks 🤔 
- We should switch from addon-info to addon-docs
- There is some kind of wrapper around sources with these weird invisible SVGs. I do not know why
**Before**
**After**

fix: show story source

---

packages/index.ts
packages/slideToggle/README.md
packages/slideToggle/components/SlideToggle.tsx
packages/slideToggle/index.ts
packages/slideToggle/stories/SlideToggle.stories.tsx
packages/slideToggle/style.ts

Added a new toggle component `SlideToggle` this is basically a checkbox
styled to be a slider with a check when checked.
I initially tried to implement this extending the ToggleComponent like
the CheckboxInput and RadioInputs do, but the styles were different
enough that I needed to make this its own component.
- Closes D2IQ-73430
Open story and try it out.

D2IQ-73430 feat: slidetoggle

---

packages/clicktocopybutton/tests/__snapshots__/ClickToCopyButton.test.tsx.snap
packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
packages/tablev2/__snapshots__/tablev2.test.tsx.snap
packages/tooltip/components/Tooltip.tsx
packages/tooltip/components/TooltipContent.tsx
packages/tooltip/stories/Tooltip.stories.tsx
packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap

- Add maxWidth for tooltips
- Add option for user to override default maxWidth to fit width to content by setting maxWidth to null (not sure if I'm 100% happy with that)
Closes D2IQ-74165
- Check out tooltip stories
This is I guess kind of a breaking change but should it _really_ be a breaking change? Let me know.

D2IQ-74165: add default maxWidth to tooltips

---

packages/expandable/components/Expandable.tsx
packages/fullscreenView/components/FullscrenView.tsx

We tried to use a more accessible form of hiding elements but that doesn't work out as easy as thought with our current integration tests. 
For the ease of implementation I decided to bring `display: none` back for now to be able to finish: https://jira.d2iq.com/browse/D2IQ-65002

fix: use `display: none` to hide closed expendable items

---

packages/styleUtils/typography/components/Text.tsx
packages/styleUtils/typography/stories/text.stories.tsx
packages/styleUtils/typography/tests/__snapshots__/typographyComponents.test.tsx.snap
packages/tablev2/__snapshots__/tablev2.test.tsx.snap

When a user sends the wrap prop with the arg of truncate, in the case
that the child is a string, output the child as the title HTML attribute
so that the user and screen readers will get the string in its entirety.
Closes D2IQ-77202

feat: title attr on truncated Text

---

packages/promo/__snapshots__/promos.test.tsx.snap
packages/promo/components/PromoBanner.tsx
packages/promo/style.ts
packages/promo/types.ts

Introducing a new oceanBlue version of the background gradient for the
PromoBanner, which has a specific implementation with three stops.
I considered an alternative of allowing this component to take a custom background color.
Closes D2IQ-77630
Have asked design to give me colors that are already in our design system rather than these three custom colors, so I will wait on them to merge this in, but the implementation can be reviewed.

feat: new promo banner background gradient

---

packages/formStructure/components/FieldList.tsx
packages/formStructure/components/FieldListContext.tsx

It seemed as though the onRemoveItem was never actually being called
based on the way that it was written, because the useEffect would not
fire, thus you'd end up with rendering issues. By tweaking a bit how
this function is called in the context, it appears to fix the issue.
I don't know why this callback function was written with the additional
closure, but I preserved it to maintain backwards compatibility.
Addresses D2IQ-77909

fix: controlled FieldList row deletion

---

.storybook/main.js
CONTRIBUTING.md
packages/breadcrumb/components/BreadcrumbItem.tsx
packages/breadcrumb/index.ts
packages/breadcrumb/stories/Breadcrumb.stories.tsx
packages/index.ts

The `BreadcrumbItem` component can be utilized to reduce common formatting utilizing FlexItems, frequently used within Kommander UI `Breadcrumb` component usage. 
`BreadcrumbItem` offers the option of an icon, url, onClick functionality, and children. All with formatted style to align with common usage. 
I have reduced the Stories to simply display the previous without and with `BreadcrumbItem`, for the sake of reducing our story files any additional examples are probably superfluous here. 
Changes to `main.js` are to ensure stories display their code examples in the Docs tab. 
I have also corrected some spelling/grammar errors in the contributing documentation while reading through for info on adding a new component. 
Closes D2IQ-65928
Run Storybook and view BreadcrumbItem story.

BreadcrumbItem Component

---

packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
packages/expandable/tests/__snapshots__/Expandable.test.tsx.snap
packages/messagePanel/tests/__snapshots__/messagePanel.test.tsx.snap
packages/messagePanel/tests/__snapshots__/messagePanelWithGraphic.test.tsx.snap
packages/promo/__snapshots__/promos.test.tsx.snap
packages/shared/styles/styleUtils/layout/flexbox.ts
packages/styleUtils/layout/flexbox/stories/flex.stories.tsx
packages/styleUtils/layout/flexbox/tests/__snapshots__/Flex.test.tsx.snap
packages/tablev2/__snapshots__/tablev2.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap

This issue was unearthed with the Emotion 11 updates. There were a few places in Kommander UI on Emotion 11 that displayed slightly off spacing, due to the padding-right and padding-bottom being added in the `Flex` component. 
It is possible that the `@support` feature query was not actually being applied until everything became updated. The feature query should be used to apply padding when the browser does not support `row-gap` or `column-gap`. According to [caniuse](https://caniuse.com/?search=column-gap) it's mostly applicable for IE and common browser versions prior to ~2017. We may decide to remove this feature query in the future if it is confirmed that we no longer need to support IE. 
[More info on how Feature Query works.](https://developer.mozilla.org/en-US/docs/Web/CSS/@support …

Fix for Flexbox spacing issues with Emotion 11 updates

---

packages/textInput/components/TextInputWithBadges.tsx
packages/toaster/components/Toaster.tsx
packages/toaster/tests/Toaster.test.tsx

Many of these errors were due to the pass-through props on the `TextInputWithBadges`.
I would like to fix the lifecycle methods more so when we are able to have time to incrementally update and convert UI Kit components. 
Check console errors while Storybook is running.

fix: for console errors found in kommander

---

packages/tabs/components/Tabs.tsx
packages/tabs/stories/Tabs.stories.tsx
packages/tabs/style.ts
packages/tabs/tests/__snapshots__/Tabs.test.tsx.snap

Closes D2IQ-62145
Updates:
- The spacing between tabs has been increased from 16px -> 24px. This aligns with the Spacing Standards in the Design System https://mesosphere.invisionapp.com/console/Kommander-GA-cknny74gbi6ql01y3t8vc22o0/cknny9h71i8fy01y3z0z129of/play
- While I was in there I decided to give the component an update to a FC, functionality remains the same after testing within Storybook.
- The Story has been updated to the new template format, there is now the option to use controls to change the direction prop.
Test the Tabs Story. 📖

Update tabs and add story controls

---

packages/dropdownMenu/components/DropdownMenu.tsx
packages/dropdownMenu/components/DropdownSection.tsx
packages/dropdownMenu/stories/Dropdown.stories.tsx
packages/dropdownMenu/tests/__snapshots__/DropdownMenu.test.tsx.snap
packages/tablev2/__snapshots__/tablev2.test.tsx.snap

We are having issues with these integrated changes on Kommander UI within the Cypress testing due to items detaching from the DOM and Cypress is unable to `cy.click()` on them. 
We can revert these changes for now and add them back again in the future with Cypress ugrades. 
Changes to reference - https://github.com/dcos-labs/ui-kit/pull/626
Open up storybook and check the dropdown menu stories.

revert dropdown menu sticky section changes

---

packages/configurationmap/components/ConfigurationMapLabel.tsx
packages/configurationmap/components/ConfigurationMapRow.tsx
packages/configurationmap/components/ConfigurationMapValue.tsx

This adds an optional `dataCy` attributes
to `ConfigurationMap{Label,Row,Value}` to be able
to search efficiently with cypress for that values
Related to D2IQ-81001

feat: add optional `dataCy` attribute

---

.releaserc
package-lock.json
package.json

This plugin was initially intended to help keep track of issues with JIRA with the open-source intentions of ui-kit. We no longer need this at the moment. However, we may choose to integrate it again in the future if the open-source aspect of ui-kit further develops. 
Will need to see how this does through Jenkins ultimately.

fix: remove semantic-release-jira plugin

---

package-lock.json
package.json

Removing node from package.json because it shouldn't need to be listed as a dependency, and also it's causing issues when trying to run `npm i` on an M1 Mac
Run `npm i` to check you can run the installs successfully. Maybe click on some of the components in the storybook to check that everything seems to be running ok.

fix(package.json): remove node dependency from package.json

---

packages/styleUtils/layout/gridList/components/GridList.tsx
packages/styleUtils/layout/gridList/stories/GridList.stories.tsx
packages/styleUtils/layout/gridList/style.ts
packages/styleUtils/layout/gridList/tests/__snapshots__/GridList.test.tsx.snap

I have done this in a way that I do not believe will break any of the styles and `GridList` usage in Kommander. Columns can still be explicitly set, have responsive options, but now will have a backup style that is a fluid grid. GridList items can be centered with a new optional prop, which provides some additional benefits such as the containers shrinking to fit their content instead of stretching. 
I've taken the opportunity here to update the story and create some useful Controls which can be used to compare to the old functionality of the GridList here - https://dcos-labs.github.io/ui-kit/?path=/story/layout-gridlist--column-count
I am still using BREAKING CHANGE to be safe, mostly due to the change in how to use some of the `GridList` props.
BREAKING CHANGE
Before this fix …

feat: improve grid features and alignment options

---

.storybook/main.js

Reordered the addons. Storybook gave a warning that addon-docs should come before addon-controls which is part of the addon-essentials pack.

fix: reorder addons to fix storybook warning

---

packages/tablev2/Table.tsx
packages/tablev2/__snapshots__/tablev2.test.tsx.snap
packages/tablev2/style.ts
packages/tablev2/tablev2.stories.tsx

Closes D2IQ-84285
If you set `contentNoWrap` false, the content of a column will allow for text wrapping instead of full truncation. 
Text will still "truncate" with the ellipsis after wrapping if it extends into overflow, as we wouldn't want something long (that cannot break) such as an email address to overlap other table cells or become cut off. We still want the user to understand that there is more text there with the ellipsis in that case.
Compare the Storybook story for Content Wrapping and ensure previous behavior on other Table stories.

feat: allow text wrapping for tables

---

packages/button/components/ButtonBase.tsx

Destructure the `openInNewTab` prop in `ButtonBase.tsx` so that it doesn't get passed down to the `button` DOM element which doesn't have that attribute.
There is some discussion about destructuring props vs filtering out invalid props. This is a quick fix until we make a final decision on how we want to handle these situations.

fix: unknown prop warning - openInNewTab

---

.storybook/docs/components/WelcomeCards.tsx
README.md
packages/themes/stories/UIKitThemeProvider.stories.tsx
packages/uiKitProvider/stories/UIKitProvider.stories.tsx

Updating our link to the design tokens to redirect to the Storybook Design Tokens. Renamed the link to be clear on this.
Removing the Dark Mode story for the UIKitThemeProvider, attached the story to fix this, it's going to require some additional research to find the best route to maintain the theme state. There may be a plugin to better handle this and apply a dark mode toggle for the entire app instead of isolating it into one story. Since the UI Kit is being inspected for the SB Encyclopedia I'd rather not have any broken stories displayed. 
Update to the README to make it a bit more clear on how to copy the dist folder into another host project.

refactor: updates for storybook site and readme

---

packages/tablev2/TooltipHeaderCell.tsx
packages/tablev2/__snapshots__/tablev2.test.tsx.snap
packages/tablev2/style.ts
packages/tablev2/tablev2.stories.tsx

Fix for alignment issues seen with table headers that include the icon for tooltips.
I've included a story to test both cases of the tooltip header in the first column and in a middle column, along with a sorter icon next to it. 
This shouldn't cause any breaking changes, the inline-flex was missing attributes to help with alignment which surfaced issues in Kommander UI. 
Icon Alignment Fix:
Wrapping Issues Fix:

fix: alignment issues in table header with icons

---

packages/dropdownMenu/components/DropdownMenu.tsx
packages/dropdownMenu/components/DropdownMenuItem.tsx
packages/dropdownMenu/components/DropdownSection.tsx
packages/formStructure/components/FieldGroup.tsx
packages/formStructure/components/FieldListColumn.tsx
packages/formStructure/components/FormMessage.tsx
packages/formStructure/components/FormSection.tsx
packages/formStructure/components/FormSectionHeader.tsx
packages/formStructure/components/FormSubSection.tsx
packages/inlineBorderedItems/components/InlineBorderedItems.tsx
packages/list/components/BorderedList.tsx
packages/loadingIndicator/components/InlineLoadingIndicator.tsx
packages/loadingIndicator/components/SectionLoadingIndicator.tsx
packages/messagePanel/components/MessagePanel.tsx
packages/messagePanel/components/MessagePanelActions.tsx
packages/messagePanel/components/MessagePanelWithGraphic.tsx
packages/messagePanel/components/MessagePanelWrapper.tsx
packages/popover/components/PopoverListItemAvatar.tsx
packages/segmentedControl/components/SegmentedControl.tsx
packages/textInputButton/components/TextInputButton.tsx

SFC is deprecated. If we want to update to React 18 we will need to first address this. I wanted to dedicate a PR to focus solely on the transition away from Stateless Functional Component.

Removing Deprecated SFC References

---

packages/accordion/__snapshots__/accordion.test.tsx.snap
packages/accordion/components/Accordion.tsx
packages/accordion/components/AccordionContext.tsx
packages/accordion/components/AccordionItem.tsx
packages/accordion/components/AccordionItemContent.tsx
packages/accordion/components/AccordionItemContext.tsx
packages/accordion/components/AccordionItemTitle.tsx
packages/accordion/components/AccordionItemTitleInner.tsx
packages/accordion/components/AccordionItemTitleOuter.tsx
packages/accordion/components/StatelessAccordion.tsx
packages/segmentedControl/components/SegmentedControl.tsx
packages/selectInput/components/SelectInput.tsx
packages/shared/components/FormFieldWrapper.tsx
packages/slideToggle/components/SlideToggle.tsx
packages/slideToggle/style.ts
packages/tablev2/Table.tsx
packages/textarea/components/Textarea.tsx
packages/toggleInput/components/ToggleInput.tsx
packages/toggleInput/style.ts
packages/toggleWrapper/components/ToggleWrapper.tsx
packages/toggleWrapper/tests/__snapshots__/ToggleWrapper.test.tsx.snap
packages/tooltip/components/Tooltip.tsx
packages/utilities/label.tsx

Closes D2IQ-64874
Changes: 
- required `id` props set to optional with dynamically created defaults with nextId()
- `data-cy` props added where applicable and given default values
- Refactored some React.FC components
- Fixed typo on: "toggleInputApperances"
Avoided any breaking changes. Required ids should already have values set in the UI. Continued the usage of any default values of data-cy.

feat: add optional id and data-cy to props

---

packages/accordion/components/Accordion.tsx

The component was getting a Typescript error when used with only a single ReactNode passed in as a child, so
the type needed to be updated to allow for for both a single ReactNode and an array of ReactNodes

fix: change type for children prop in the Accordian component

---

package-lock.json
package.json
packages/modal/tests/__snapshots__/Modal.test.tsx.snap
packages/popover/tests/__snapshots__/Popover.test.tsx.snap

With this update, the div with tabIndex="1" is removed from the snapshot. This is a good indicator that it will be our fix in the UI based on the a11y violation that tabIndex values should not be greater than 0.

Fix for tabIndex values with updated react-focus-lock versioning

---

packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
packages/expandable/tests/__snapshots__/Expandable.test.tsx.snap
packages/messagePanel/tests/__snapshots__/messagePanel.test.tsx.snap
packages/messagePanel/tests/__snapshots__/messagePanelWithGraphic.test.tsx.snap
packages/pagination/__snapshots__/pagination.test.tsx.snap
packages/popover/tests/__snapshots__/PopoverListItem.test.tsx.snap
packages/progressbar/tests/__snapshots__/ProgressBar.test.tsx.snap
packages/promo/__snapshots__/promos.test.tsx.snap
packages/styleUtils/layout/flexbox/components/Flex.tsx
packages/styleUtils/layout/flexbox/components/FlexItem.tsx
packages/styleUtils/layout/flexbox/tests/__snapshots__/Flex.test.tsx.snap
packages/tablev2/__snapshots__/tablev2.test.tsx.snap
packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap

React 18 is not a fan of React.FC usage. I am testing out the refactoring of this component to help troubleshoot the transition of @types/react. I've made a point to add a customizable data-cy prop for `Flex` and `FlexItem`.
The snapshots have changed but I am still setting defaultProps in the component. The before and after comparison remains the same. You can see these props set when inspecting the elements.
Before:
After:

fix: testing fix for react18 prop updates

---

packages/badge/components/badgeButton.tsx

This is a fix for the `children` props on `BadgeButton` which should allow a string or any elements we pass in. This can be covered with the use of `React.ReactNode` which is consistent with other `children` props in ui-kit. Took the opportunity here to allow for a customizable data-cy prop as well.

fix: badgebutton children and data-cy props

---

packages/messagePanel/tests/__snapshots__/messagePanel.test.tsx.snap
packages/messagePanel/tests/__snapshots__/messagePanelWithGraphic.test.tsx.snap
packages/promo/__snapshots__/promos.test.tsx.snap
packages/shared/styles/styleUtils/layout/flexbox.ts
packages/styleUtils/layout/flexbox/components/Flex.tsx
packages/tablev2/__snapshots__/tablev2.test.tsx.snap

Adding the gap property to the Flex component so the gutter size for columns and rows can be set with a single value.
Closes D2IQ-90211
I've added the style for `gap` just below where `column-gap` and `row-gap` are set so that if `gap` is set, it will override the other values. I'm not sure if this is the best solution, but it was certainly the easiest.

feat: add gap property to flex component

---

packages/pagination/__snapshots__/pagination.test.tsx.snap
packages/segmentedControl/components/SegmentedControlButton.tsx
packages/segmentedControl/tests/__snapshots__/SegmentedControl.test.tsx.snap
packages/selectInput/components/SelectInput.tsx
packages/selectInput/tests/SelectInput.test.tsx
packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap

Refactoring some form PureComponents to be functions instead. One thing
that tripped me up was that the refactor of SelectInput threw warnings
if appearance was a required prop. Not sure how this wasn't throwing
warnings before. Either way though, because it is defaulted, making
it an optional prop is still backwards compatible.

refactor: form controls to functions

---

packages/checkboxInput/components/CheckboxInput.tsx

Closes D2IQ-92602
This change is a request from the product design team. We should clarify the usage of the indeterminate prop. 
Changes include a quick update to the definition of indeterminate, and a refactor to remove React.FC. 
https://jira.d2iq.com/browse/D2IQ-92602

refactor: indeterminate definition and prop typing

---

packages/tabs/components/Tabs.tsx

This is a PR that results contains the changes for the tab component to be more usable: https://github.com/mesosphere/kommander-ui/pull/4367#discussion_r966883739
* Make `onSelect` optional
* Make `selectedIndex` optional
* Let the children be an array or a single element
I did not create a separate story for this but tested that it works on the existing story by temporarily removing these props.

refactor: make onSelect and selectedIndex props optional

---

packages/tabs/components/Tabs.tsx

This removes the default values from the function definition and is a `fix` commit to trigger a release.

fix: dont use default props for `selectedIndex` and `onSelect`

---

packages/selectInput/components/SelectInput.tsx

The property `inputLabel` was effectively optional before (I do not exactly know why, the types say otherwise).
The issue needs have to been introduced somewhere in this PR: https://github.com/dcos-labs/ui-kit/pull/756
When using storybook 11.0.0 everything is fine, but when updating to 11.0.1 I get type errors on components which are using the `SelectInput`.
As I do not want to touch all the places in kommander-ui where this is happening I think the best way is to make it optional here.

fix: make `inputLabel` optional

---

tsconfig.designTokens.json
tsconfig.dist.json

We have introduced type checks and therefore changed our tsconfig file to only emit types to be faster.
Our dist tsconfig file extends this other file so no javascript files were transpiled

fix: let `dist` command output transpiled js

---

packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
packages/fullscreenView/tests/__snapshots__/fullscreenView.test.tsx.snap
packages/link/components/Link.tsx
packages/link/components/ResetLink.tsx
packages/link/components/UnstyledLink.tsx
packages/link/stories/link.stories.tsx
packages/link/types.ts
packages/modal/tests/__snapshots__/Modal.test.tsx.snap
packages/shared/components/FocusStyleManager.tsx
packages/themes/components/UIKitThemeProvider.tsx
packages/uiKitProvider/components/UIKitProvider.tsx
packages/uiKitProvider/stories/helpers/customLink.tsx

Converting link components to functional components with updated types and additional cleanup.
Refactoring the components to move away from class components and better prop types to prepare for React 18.
Refactored components include:
- FocusStyleManager
- UnstyledLink
- Link
- UIKItProvider
- UIKitThemeProvider
- customLink
Some of these components impact each other which is why they are grouped together in these changes.
Regression testing on the stories for the components listed above. 
Button components should have the same functionality, they should still have an outline or underline with keyboard navigation.

refactor: link components

---

packages/typeahead/components/Typeahead.tsx
packages/typeahead/stories/helpers/FilteredListTypeahead.tsx
packages/typeahead/tests/Typeahead.test.tsx
packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap

This one was more complicated but converted Typeahead from a class component to a functional component. All functionality should be preserved, but I did find that the CustomMenuEmptyState story did not work as expected because the empty state should be shown when there are no items. Also made a decision to remove the filteredlist typeahead because it didn't really demonstrate any functionality of the component itself, just of how a wrapping component could control its state. It seemed superfluous.
This one had pretty good unit test coverage, but a regression of the typeahead stories against prod would be good

refactor: typeahead component and stories

---

packages/textarea/components/Textarea.tsx

Refactor Textarea from a class component to a function component
https://github.com/dcos-labs/ui-kit/issues/790
Testing can be done via storybook and by running unit tests.
None
Not needed.

refactor: refactor Textarea into a functional component

---

packages/accordion/components/AccordionItemTitleInteractive.tsx
packages/clicktocopybutton/components/ClickToCopy.tsx
packages/clicktocopybutton/components/ClickToCopyButton.tsx
packages/clicktocopybutton/tests/__snapshots__/ClickToCopyButton.test.tsx.snap
packages/codesnippet/components/CodeSnippet.tsx
packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
packages/dropdownable/components/Dropdownable.tsx
packages/expandable/components/Expandable.tsx
packages/expandable/tests/__snapshots__/Expandable.test.tsx.snap
packages/formStructure/components/FieldList.tsx
packages/formStructure/components/FieldListAddButton.tsx
packages/formStructure/components/FieldListColumn.tsx
packages/formStructure/components/FieldListContext.tsx
packages/formStructure/components/FormMessage.tsx
packages/formStructure/components/FormSectionFooter.tsx
packages/formStructure/components/FormTitle.tsx
packages/infobox/components/InfoBox.tsx
packages/inlineBorderedItems/components/InlineBorderedItems.tsx
packages/modal/components/ModalContents.tsx
packages/pagination/PaginationContainer.tsx
packages/pagination/pagination.stories.tsx
packages/promo/components/PromoBanner.tsx
packages/promo/components/PromoContent.tsx
packages/radioInput/RadioInput.tsx
packages/slideToggle/components/SlideToggle.tsx
packages/tablev2/MutedCell.tsx
packages/utilities/label.tsx
scripts/templates/component/Component.tsx

Due to the issues with implicit children with React.FC we have decided to migrate components away from using this. 
This causes some interfaces to now include a prop-type definition for children. I wanted to isolate this refactor. This should take care of every last reference to React.FC or React.FunctionComponent. 
These changes will pave the way for our full migration to React 18.
I've also included a select few refactors for `defaultProps` when I noticed them.

refactor: migration away from react.fc

---

packages/infobox/stories/InfoBox.stories.tsx
packages/infobox/stories/InfoBoxBanner.stories.tsx

This PR adds a control for the message property to the `InfoBox` and `InfoBoxBanner` stories, and also adds a type to the template so we can remove the message prop where the `InfoBox` is used.
Go to `InfoBox` and `InfoBoxBanner` stories in Storybook and confirm that they message control works
I haven't added the message control to the `InfoBoxInline` stories because one of the stories uses custom markup and I'm not sure what's the best way to allow users to control this in a way that is intuitive, and I'm not sure if it's even possible.

feat: add message control to infobox stories

---

packages/configurationmap/tests/ConfigurationMap.test.tsx
packages/configurationmap/tests/__snapshots__/ConfigurationMap.test.tsx.snap

This PR converts the `ConfigurationMap` component tests from Enzyme to React Testing Library. 
I don't have any experience with Enzyme or RTL, so I wanted to get involved with the conversions so I could learn how to use RTL.
I removed `create` from `react-test-renderer` and replaced it with `asFragment`. I'm not really sure why we were using `react-test-renderer` here, but it was only added about 3 weeks ago by @vacas5, so if this is preferable to `asFragment` please say!

refactor: convert ConfigurationMap tests from enzyme to RTL

---

packages/fullscreenView/components/FullscreenView.tsx
packages/fullscreenView/stories/fullscreenView.stories.tsx
packages/modal/tests/__snapshots__/Modal.test.tsx.snap

If child content of FullscreenView is wrapped in a container, it would be nice to be able to contain the header of this component also for visual consistency. Opted to keep the padding as is and just account for it in the max width so that consumers can pass in our design tokens as is without having to do the math themselves to account for the padding left and right.
Addresses D2IQ-92266
https://d2iq.atlassian.net/browse/D2IQ-92266
Created a new story for this use case.
Accounting for padding from within the component. May be confusing to the user but border-box would be the alternative and I'm not sure if that would have fallout.

feat: optional max-width for FullscreenView header

---

packages/breadcrumb/components/Breadcrumb.tsx
packages/card/components/ButtonCard.tsx
packages/card/components/Card.tsx
packages/card/components/LinkCard.tsx
packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
packages/configurationmap/components/HashMap.tsx
packages/donutChart/components/DonutChart.tsx
packages/formStructure/components/FieldList.tsx
packages/formStructure/stories/helpers/FieldListStoryHelper.tsx
packages/modal/components/FullscreenModal.tsx
packages/modal/tests/__snapshots__/Modal.test.tsx.snap
packages/pageheader/components/PageHeader.tsx
packages/pagination/__snapshots__/pagination.test.tsx.snap
packages/segmentedControl/components/SegmentedControlButton.tsx
packages/segmentedControl/stories/helpers/SegmentedControlStoryHelper.tsx
packages/segmentedControl/tests/__snapshots__/SegmentedControl.test.tsx.snap
packages/selectInput/components/SelectInput.tsx
packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap
packages/tablev2/__snapshots__/tablev2.test.tsx.snap
packages/textInput/stories/helpers/TextInputWithBadgesStoryHelper.tsx
packages/tooltip/components/TooltipContent.tsx
packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
packages/typeahead/components/Typeahead.tsx
packages/typeahead/stories/helpers/FilteredListTypeahead.tsx

When we memoize components, we should set `React.memo()` around the component export so that it does not affect the storybook code snippets under the Docs tab.
This will keep our use of React.memo consistent throughout the project. 
before
after

refactor: move wrapping react.memo to export

---

packages/fullscreenView/components/FullscreenView.tsx
packages/fullscreenView/stories/fullscreenView.stories.tsx

In order to support responsive layouts and different container sizes at various widths, this really should just take a classname so that a client has total control. I tried to borrow the container classname from the container component and go with a boolean argument like "contained" but I found that our usage in DKP needed to change the box-sizing anyway to get it to be consistent. Rather than have both props, just went with one, more versatile prop.

fix: contain FullscreenView with classname

---

packages/textInput/components/TextInput.tsx
packages/textInput/components/TextInputWithBadges.tsx
packages/textInput/components/TextInputWithButtons.tsx
packages/textInput/components/TextInputWithIcon.tsx
packages/textInput/components/utils.tsx

This PR changes the following components from being class based ones, to be functional ones:
- `TextInput`
- `TextInputWithIcon`
- `TextInputWithBadges`
- `TextInputWithButton`
As a side effect of changing the paradigm (ineritance within components), we've created a new file called `utils.ts`, where some shared logic among these components is placed.
closes #800 
A single regression test of the 4 elements mentioned above should be enough for it.
There are still some duplicated code between components, such as the following functions:
`getInputAppearance`, we might need to refactor these as well, but since these depends on a state (`hasFocus`) didn't feel in the mood to refactor them.
Same as before 🙂

Refactor TextInput related components from classes to functional components

---

packages/popover/components/Popover.tsx
packages/progressbar/components/ProgressBar.tsx
packages/promo/components/PromoInline.tsx
packages/styleUtils/layout/stack/components/Stack.tsx
packages/styleUtils/typography/components/TextBlock.tsx
packages/tablev2/DropdownMenuCell.tsx
packages/tablev2/TooltipHeaderCell.tsx

React.StatelessComponent is deprecated.
React.StatelessComponent is deprecated and should not be used. We will need to make this change before we're able to update to React 18.

refactor: remove statelesscomponent use

---

packages/modal/components/DialogModal.tsx
packages/modal/components/DialogModalWithFooter.tsx
packages/modal/components/ModalBase.tsx
packages/modal/tests/__snapshots__/Modal.test.tsx.snap

Migrates DialogModal and related components to FunctionComponent.
Components:
- DialogModal
- DialogModalWithFooter
- ModalBase
#784
Run Jest Tests via `$ npm run test` and via Storybook.
Behaviours:
- Modal defaults to being animated
- Clicking outside does not close the Modal
- Clicking on X or pressing escape closes the Modal
N/A
N/A
- [`modal/components/helpers/ModalExample.tsx` is an empty file ](https://github.com/dcos-labs/ui-kit/blob/main/packages/modal/components/helpers/ModalExample.tsx)
- Modal z-index is set to 1

refactor: DialogModal to Function Component

---

packages/button/components/ButtonBase.tsx
packages/link/components/UnstyledLink.tsx
packages/link/types.ts
packages/pagination/__snapshots__/pagination.test.tsx.snap

Consuming LinkComponent has been a challenge downstream. We don't actually need the focus style manager to handle unstyled links as far as I can tell, so the console warnings should be resolved without having to keep drilling down into child Link components.

fix: rollback ref on unstyled link

---

packages/toggleWrapper/components/ToggleWrapper.tsx

React does not allow checked prop on uncontrolled components. Need to use defaultChecked. This quiets the consoles showing up when running tests.
Regression test ToggleBox

fix: console error for togglewrapper

---

packages/toaster/components/Toast.tsx
packages/toaster/tests/Toast.test.tsx
packages/toaster/tests/__snapshots__/Toast.test.tsx.snap

The toast test suite was tightly coupled with Toaster. This may have been a copy paste issue or something, but the snapshots didn't even reflect the markup of the Toast component. I have removed the wrapping of each of these in Toaster, and a couple of tests that were targeting behavior of Toaster rather than Toast. I have refactored to use RTL instead of enzyme in other cases.

test: clean up toast test suite

---

packages/toaster/stories/Toaster.stories.tsx

During a separate refactor I found a bug in how I did the stories for Toaster. Autodismiss should dismiss one at a time rather than all at once. I think this is a bit more conventional react anyway. Also added a story for multiple toasts at the same time.
Toaster stories, particularly autodismiss
https://user-images.githubusercontent.com/815936/198899003-c646e9e1-4ce9-4283-b4d3-e85ac9d86c30.mov

fix: toaster stories

---

packages/tablev2/__snapshots__/tablev2.test.tsx.snap
packages/tablev2/style.ts

The chevron is bumped down below the header title when a header tooltip is present.
Closes D2IQ-94167
With the changes to the chevron to allow it to be clickable, a bug was introduced that forced the chevron down below the header title when there is also a header tooltip present on hover. Setting the display from flex to flex-inline will keep things _inline_ and preserves Table component functionality. 
Check the Column Header With Tooltip story under the Table component. 
Use `npm link` to test within the UI. 
Before
After
Tested in the UI with `npm link`

fix: sorter chevron alignment in table header

---

packages/tabs/components/Tabs.tsx
packages/tabs/stories/Tabs.stories.tsx

This commit adds a useMemo to the Tabs component so that we can use a UUID for the keys of the Tabs children. The UUID allows us to generate a unique key, while the useMemo prevents the UUID from being recalculated unless the children change.
Closes D2IQ-92719
https://d2iq.atlassian.net/browse/D2IQ-92719
I've changed the story so that the first Tab has 2 non-TableTitle children. You should be able to view the Tab story in Storybook without seeing any console warnings.
The issue here is that the key for the Tab child components was being set by a const outside of the map, which meant that all children were getting set with the same key. We tried to use `object-hash` to turn the child into a hash and use that as the key but there were type issues with turning a ReactElement into a hash. …

fix: duplicate key in tabs component

---

packages/tabs/components/Tabs.tsx
packages/tabs/stories/Tabs.stories.tsx

When we have a form inside a tab component the tab component rerenders because the key change every time the children changes. This leads to input fields losing focus and other issues.
This uses the `index` as a key, which is not necessarily best practice but it removes the previously existing duplicated key error and fixes the rerender issue.

Fix Tab Component again

---

packages/dropdownMenu/components/DropdownMenu.tsx
packages/popover/components/PopoverBox.tsx
packages/popover/style.ts

Allow height and width types to accept any valid
CSS height/width properties such as vw, ems,
and other string values beyond numbers.
I encountered this when attempting to use a value with `vh` where I got a type error. These values should accept any valid related CSS height or width property, such as ems, rems, vh, vw, etc.  Followed the trail up to the `PopoverBox` and update those types there too. 
Included a few other tweaks in here too such as a typo fix, and a className prop for the Dropdown. 
Note: The `React.CSSProperties` type will handle strings or numbers so there will not be a breaking change. 
Emotion will append `px` if only a number is passed in. 
You can update one of these values in the Storybook story. 
I also tested this out using `npm link` in the UI.

fix: allow valid css height/width types

---

packages/dropdownMenu/components/DropdownMenu.tsx
packages/dropdownMenu/components/DropdownSection.tsx
packages/dropdownMenu/stories/Dropdown.stories.tsx

I'd like to re-introduce some changes that I made a while back to allow for a sticky section in the footer of the dropdown menu. This will allow for a section of important items to always be available as a user scrolls through the menu.
Original implementation - https://github.com/dcos-labs/ui-kit/pull/626
We had reverted this due to some cypress test failures in the UI, which at this point were likely just flakes at the time.

feat: sticky footer section for dropdown

---

packages/toaster/components/Toaster.tsx
packages/toaster/stories/Toaster.stories.tsx
packages/toaster/tests/Toaster.test.tsx

This PR updates the Toaster component so that it can take a custom timeout value
**NOTE** I'm going to put the story updates for this component in a separate PR because I have questions about some funky behavior I'm seeing and I don't want it to hold up this insights toast ticket.
https://d2iq.atlassian.net/browse/D2IQ-94241

feat: Toast - add a custom timeout

---

.github/workflows/uffizzi-build.yml
.github/workflows/uffizzi-preview.yml

Seeing more failures with GitHub actions. We haven't been generating Uffizzi previews and there have been some failures.
We need to update the `UffizziCloud/preview-action/.github/workflows/reusable.yaml` to use `@2` to keep up-to-date with the latest changes to the reusable workflow. We will need to merge this PR into main to confirm the changes. Workflows dispatched by the `workflow_run` event always use the definition in the default branch, which is main for us. 
This change was suggested by the Uffizzi team. 
Merge these changes to test.

update uffizzi preview actions

---

packages/button/stories/DefaultButton.stories.tsx

Monica pointed out that we have two stories here that are essentially the same - Thanks Monica! 
I've consolidated them down to a `WithIcons` story that displays the `iconStart` and `iconEnd` together.
I've found a better way to configure the icon-related controls so that we can display all of the available system icons and it will have a label that is similar to how it would be used by a developer ie the key `ArrowUp` vs the value `"system-icons-arrow-up"`.
Test out the icon controls on the "With Icons" story. You can test through the Uffizzi preview or run Storybook locally.

refactor: button stories with icons

---

packages/appChrome/components/AppChrome.tsx

Allows for someone to use just the header or sidebar without needing to declare both. Also add children prop and deprecates mainContent because its a lot easier to use with children, as it allows JSX to simply be nested rather than part of a prop. Found these while trying to use this component during innovation days.

feat: make appchrome props optional

---

packages/utilities/getCSSVarValue.ts

document and window are not defined in node environments, so trying to use ui-kit with an isomorphic framework like next will fail saying document/window is not defined. Adding a check that window is not undefined before trying to operate on document seems to fix the issue. There may be more places like this in ui-kit but this is all I've run up against so far.

fix: make var check ssr friendly

---

packages/loadingIndicator/components/InlineLoadingIndicator.tsx
packages/loadingIndicator/stories/InlineLoadingIndicator.stories.tsx
packages/loadingIndicator/tests/__snapshots__/loadingIndicator.test.tsx.snap

Introduces custom color, size, and data-cy props.
Previous to these changes our `InlineLoadingIndicator` component has been pretty rigid. It would only be the black/default/inherited color. You could not customize the size or color. 
After these changes, we can customize this component's color, size, and data-cy while maintaining the previous defaults. 
This allows for a more extensible component.
I've also fixed up the stories here. It's easier to see the component's code block, customize controls, and see the component on its own as a default.
Check out the stories in the Uffizzi link.

feat: inlineloadingindicator custom props

---

package-lock.json
package.json
packages/tabs/components/Tabs.tsx

Closes D2IQ-94906
This initial issue arose from noticing a gray background on Tab Items in the UI after they've been clicked on. After looking into this issue, I discovered this behavior was coming from the `:focus` style set for the Tabs component upstream. It was an intentional style decision to handle keyboard navigation to display active focus.
After looking into the functionality of the `:focus` pseudo-class. I discovered `:focus-visible` which applies the style when elements are interacted with via keyboard and not with pointer-events such as mouse clicks. This seemed like the perfect resolution for our situation. We do not want the gray background on click but we do want it for keyboard navigation to preserve accessibility.
Resource: [The :focus-visible …

fix: react tabs focus styling

---

packages/accordion/components/AccordionItem.tsx
packages/accordion/components/AccordionItemContent.tsx
packages/accordion/components/AccordionItemTitle.tsx
packages/accordion/components/AccordionItemTitleInner.tsx
packages/accordion/components/AccordionItemTitleInteractive.tsx
packages/accordion/components/AccordionItemTitleOuter.tsx
packages/accordion/types.ts
packages/appChrome/components/AppChrome.tsx
packages/avatar/components/Avatar.tsx
packages/badge/components/badge.tsx
packages/badge/components/badgeButton.tsx
packages/breadcrumb/components/Breadcrumb.tsx
packages/button/components/ButtonBase.tsx
packages/card/components/ButtonCard.tsx
packages/card/components/Card.tsx
packages/clickable/components/clickable.tsx
packages/configurationmap/components/ConfigurationMapValue.tsx
packages/donutChart/components/DonutChart.tsx
packages/dropdownMenu/components/DropdownMenu.tsx
packages/list/components/BorderedList.tsx
packages/list/components/List.tsx
packages/loadingIndicator/components/SectionLoadingIndicator.tsx
packages/messagePanel/components/MessagePanel.tsx
packages/messagePanel/tests/__snapshots__/messagePanel.test.tsx.snap
packages/styleUtils/modifiers/components/BorderedBox.tsx
packages/styleUtils/modifiers/components/Box.tsx
packages/styleUtils/modifiers/components/SpacingBox.tsx
packages/utilities/label.tsx

Throughout these changes I am looking to achieve the following:
- Add `data-cy` attributes that we will be able to pass in custom values. Improving DX with our components + Cypress testing. I have opted for consistent use of `"data-cy"` instead of `["data-cy"]` as the [] is unnecessary. 
- Add `className` to an outermost container on components, that we can use for style overrides in the future.
- Consistency in the casing of prop definitions, as this displays to the Storybook UI in the Docs tab.
- Remove unnecessary `defaultProps` and opt for default values set during prop destructuring.

[1] refactor: add data-cy and classname props

---

packages/accordion/components/AccordionItemTitleInner.tsx
packages/card/components/LinkCard.tsx
packages/formStructure/components/FormMessage.tsx
packages/formStructure/components/FormSection.tsx
packages/formStructure/components/FormSectionFooter.tsx
packages/formStructure/components/FormSectionHeader.tsx
packages/formStructure/components/FormTitle.tsx
packages/icon/components/Icon.tsx
packages/infobox/components/InfoBox.tsx
packages/messagePanel/components/MessagePanelWithGraphic.tsx
packages/modal/components/FullscreenModal.tsx
packages/modal/components/ModalBase.tsx
packages/modal/components/ModalContents.tsx
packages/pageheader/components/PageHeader.tsx
packages/popover/components/Popover.tsx
packages/popover/components/PopoverBox.tsx
packages/popover/components/PopoverListItem.tsx
packages/promo/types.ts
packages/styleUtils/layout/flexbox/components/Flex.tsx
packages/styleUtils/layout/flexbox/components/FlexItem.tsx
packages/styleUtils/layout/gridList/components/GridList.tsx

Throughout these changes I am looking to achieve the following:
- Add `data-cy` attributes that we will be able to pass in custom values. Improving DX with our components + Cypress testing. I have opted for consistent use of `"data-cy"` instead of `["data-cy"]` as the [] is unnecessary. 
- Add `className` to an outermost container on components, that we can use for style overrides in the future.
- Consistency in the casing of prop definitions, as this displays to the Storybook UI in the Docs tab.
- Remove unnecessary `defaultProps` and opt for default values set during prop destructuring.

[2] refactor: add data-cy and classname props

---

packages/appChrome/components/SidebarSection.tsx
packages/button/components/DangerButton.tsx
packages/button/components/DangerDropdownButton.tsx
packages/button/components/PrimaryButton.tsx
packages/button/components/PrimaryDropdownButton.tsx
packages/button/components/SecondaryButton.tsx
packages/button/components/SecondaryDropdownButton.tsx
packages/button/components/StandardButton.tsx
packages/button/components/StandardDropdownButton.tsx
packages/button/components/SuccessButton.tsx
packages/button/components/SuccessDropdownButton.tsx
packages/segmentedControl/components/SegmentedControl.tsx
packages/segmentedControl/components/SegmentedControlButton.tsx
packages/styleUtils/layout/stack/components/Stack.tsx
packages/styleUtils/typography/components/CaptionText.tsx
packages/styleUtils/typography/components/SmallText.tsx
packages/styleUtils/typography/components/Text.tsx
packages/styleUtils/typography/textTypes.ts
packages/tabs/components/Tabs.tsx
packages/textInput/components/TextInputWithBadges.tsx
packages/toaster/components/Toast.tsx
packages/toaster/components/Toaster.tsx
packages/toggleInput/components/ToggleInput.tsx
packages/toggleWrapper/components/ToggleWrapper.tsx
packages/tooltip/components/Tooltip.tsx
packages/tooltip/components/TooltipContent.tsx
packages/typeahead/components/Typeahead.tsx

Throughout these changes I am looking to achieve the following:
- Add `data-cy` attributes that we will be able to pass in custom values. Improving DX with our components + Cypress testing. I have opted for consistent use of `"data-cy"` instead of `["data-cy"]` as the [] is unnecessary. 
- Add `className` to an outermost container on components, that we can use for style overrides in the future.
- Consistency in the casing of prop definitions, as this displays to the Storybook UI in the Docs tab.
- Remove unnecessary `defaultProps` and opt for default values set during prop destructuring.

[3] refactor: add data-cy and classname props

---

.github/CODEOWNERS

The file got auto-formatted at some point and changed the `*` to a `-` thinking it was a bullet point. The `*` is necessary and represents all the files present in the repo.
This will allow the d2iq/ui-team to be set as the default code reviewers on PRs.
I don't think we can fully test this until after it is merged in.

fix: set ui team as default code reviewer

---

packages/tooltip/components/TooltipContent.tsx

The tooltip style has been affected by the placement of the className prop.

fix: classname placement in cx function

---

packages/list/components/List.tsx

The tag property has always had a fallback/default value of "ul". Because of this, the property should be optional to set. Moving the from defaultProps to using fallbacks triggered this requirement.

feat: list tag prop is optional

---

packages/card/components/ButtonCard.tsx
packages/clickable/README.md
packages/clickable/components/clickable.tsx
packages/clickable/tests/clickable.test.tsx
packages/textInput/components/TextInputWithBadges.tsx

This changes all uses of `onKeyPress` to `onKeyDown` in `ButtonCard`, `clickable`, and `TextInputWithBadges`. I have also renamed a few functions that contain key press in the name to key down for consistency as well as replaced references of `onKeyPress` to be `onKeyDown`.
#915 
Storybook and run tests

refactor: change all onKeyPress uses to use onKeyDown instead

---

packages/segmentedControl/style.ts
packages/segmentedControl/tests/__snapshots__/SegmentedControl.test.tsx.snap

The height of the SegmentedControl is not consistent with other elements. It should align with other components such as buttons, and form elements.
Closes D2IQ-95243
The height of the SegementedControl component is slightly larger than other components. 
There are some extra height calculations happening in this component due to `line-height` that is just enough to set it off by a few pixels.
This will help the component to look in line with other form elements that we'd like to place it next to. 
If you'd like to double-check the work, you can inspect the SegmentedControl and the height should be around 36px instead of 39. 
**Here is a side-by-side of a before and after.**
**Before**
**After**

fix: height of segmentedcontrol

---

packages/messagePanel/tests/__snapshots__/messagePanel.test.tsx.snap
packages/styleUtils/modifiers/components/SpacingBox.tsx

Looks like when we changed default props tag wasn't passed in properly.

fix: fixed tag default prop for spacing box

---

packages/avatar/style.ts
packages/avatar/tests/__snapshots__/avatar.test.tsx.snap
packages/progressbar/components/ProgressBar.tsx
packages/progressbar/style.ts
packages/progressbar/tests/__snapshots__/ProgressBar.test.tsx.snap

There are some issues with borders set as % vs px.
This [issue](https://stackoverflow.com/questions/18794947/capsule-shape-using-border-radius-without-a-set-width-or-height) basically sums up the fix with percentage-based border-radius for a pill/capsule shape.
The Avatar shape issues were less obvious as they did not appear in the story but they will be affected in the UI after some testing, reverted back to 25% as a fix. 
Added a custom data-cy for the progress bar also.

fix: shape of progressbar and avatar

---

.github/workflows/ci.yml

As `dist` is running anyway, which runs `tsc`, which includes a type
check and we need to run `dist` before or rather
`predist`/`build:design-tokens` before we are able to run `test:types`
I decided to remove the `test:types` check from CI.
Produce a type error and run `npm run dist` locally.

ci: run type checking earlier

---

packages/selectInput/components/SelectInput.tsx
packages/selectInput/tests/SelectInput.test.tsx
packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap

This adds the disabled prop to `SelectInput`. This is not working before. I also added something to the test to make sure it is disabled.
- https://jira.d2iq.com/browse/D2IQ-96288
Add a disabled tag to a SelectInput and make sure it works.

fix: fix disabled not working on select input

---

packages/selectInput/components/SelectInput.tsx
packages/styleUtils/typography/components/SmallText.tsx

This also fixes a required prop in SmallText, which causes type problems in kommander ui.
Make sure SmallText and SelectInput work.

fix: fix required for select input

---

packages/textInput/components/TextInputWithButtons.tsx
packages/textInput/stories/TextInputWithButtons.stories.tsx

This fixes the story controls so that it doesn't freeze when you change the appearance.
I've refactored this again as I've discovered the intended behavior here is that the  `iconStart` will take on the color of the input. However, the button can take on its own color. I've added a comment to clarify this for the future.

refactor: TextInputWithButtons story

---

packages/shared/styles/color.ts

Ensure that getTextColor is choosing colors with better contrast.
QA noticed that using this color #005E70 for a background color opted for a dark text color. This does not pass WCAG 2.0 AA compliance of a 4.5:1 contrast ratio for normal text. Therefore the text was hard to read on the background color. 
I've adjusted and tested this function so that it will perform better and choose the text color with a higher color contrast.
The best way to test this would be to bring it in downstream. So either copy/paste the function over in the code or try to use npm link. 
This function is pretty complex 😅

fix: recalibrate getTextColor function

---

packages/modal/style.ts

The change in #982 doesn't work as expected for the original issue.
* Install the newest (15.0.0) ui-kit version
* Go to the kommander-default-workspace
* Disable cert-manager
* Edit traefik (change configuration) and hit save to see the modal
* see the editor still overalying the modal
Apply ui-kit changes from this PR like you usually do (npm link or copying files) and rerun the testing step, except the first one to install ui-kit. In the last step you should see the modal on top of the editor.
before 
after

fix: set z-index for center dialog wrapper

---

packages/textInput/stories/TextInputWithIcon.stories.tsx

Updating this component story to be a better,
example of how this component may be used.
The search magnifying glass is a good example.
I'd like to change the default icon here to something that is a bit more exemplarily on how you'd normally use this component. 
We had this TriangleDown icon set here as the default.
I think this adds confusion as it makes it seem like it's a dropdown. 
These text inputs can often be used for search so this is a better example use case. 
View the TextInputWithIcons story.

docs: update to use search icon by default

---

.storybook/theme.js

Updated storybook theming to use design token values.
With this work I reviewed if there were any changes to how storybook handles theming overrides with v7.
It was all about the same, though I did find some new values for example `brandTarget: "_self",` which is applicable for us because when clicking the logo it takes you to the home page. 
The "_self" value for the target attribute indicates that the linked content should be displayed in the same browsing context or the same window/tab where the link was clicked.
We need to use the getCSSVarValue function here because of how our theming DS are formatted - `export const themeBrandPrimary: string = "var(--themeBrandPrimary, #7D58FF)";` 
Otherwise you'll see this error `Uncaught Error: Couldn't parse the color string. Please provide the …

docs: storybook theming values

---

packages/breadcrumb/stories/Breadcrumb.stories.tsx

This update improves the icon control for the Breadcrumb story. 
Before you could only select from 3 options. Now you can select from any ProductIcon.
I've filtered out the inverse versions of product icons because this story has a white background and I don't think we need to include those here otherwise it will look like nothing is displaying.
Switch up some icons for the Breadcrumbs.
Before
After

docs: access to all product icons for breadcrumb

---

.storybook/docs/stories/Spacing.stories.mdx
.storybook/main.ts

This story adds a reference to our sizing design tokens, the values they represent, along with a visual representation of each.
When I speak with the design team we often talk in pixels and I have to translate that into our design tokens when building the UI. 
I have a notes app on my computer where I have a reference to each sizing token and the amount of px they are.
```
| spaceXxs         | 4px   |
| spaceXs          | 8px   |
| spaceS           | 12px  |
| spaceM           | 16px  |
| spaceL           | 24px  |
| spaceXl          | 32px  |
| spaceXxl         | 48px  |
```
My main hope is that this page will be a helpful reference for others,  and so these don't just have to live in my notes app. 
I think it's nice to see a visual representation of the scale. 
FYI Storybook has some …

docs: introduces spacing docs

---

package-lock.json
package.json
packages/popover/components/PopoverListItem.tsx
packages/typeahead/components/Typeahead.tsx

- Currently, downshift version is [8.2.2](https://www.npmjs.com/package/downshift).
- Since the [width](https://github.com/d2iq/ui-kit/blob/main/packages/popover/components/PopoverBox.tsx#L33) accepts only `number | undefined` made changes accordingly to pass `undefined`.
- Since the is [Selected](https://github.com/d2iq/ui-kit/blob/main/packages/popover/components/PopoverListItem.tsx#L31) was accepting `boolean | undefined` made changes accordingly to pass `null` as we cannot changed the type of [selectedItem](https://github.com/d2iq/ui-kit/blob/main/packages/typeahead/components/Typeahead.tsx#L243) as it is coming from [downshift](https://github.com/downshift-js/downshift/blob/master/typings/index.d.ts#L11) library.
https://github.com/d2iq/ui-kit/issues/985
- Tested the `Typeahead` …

chore(deps): bump downshift from 7.6.0 to 8.2.2

---

packages/button/README.md
packages/button/components/ButtonBase.tsx
packages/button/components/OutlineButton.tsx
packages/button/components/OutlineDropdownButton.tsx
packages/button/index.ts
packages/button/stories/DefaultButton.stories.tsx
packages/button/stories/DropdownButton.stories.tsx
packages/button/style.ts
packages/button/tests/__snapshots__/ButtonBase.test.tsx.snap
packages/index.ts

Introduces a new OutlineButton component,
along with an OutlineDropdownButton.
Closes D2IQ-99363
2 New Components
- `OutlineButton`
- `OutlineDropdownButton`
We wanted to introduce this new OutlineButton to serve as a secondary button, for example there are locations in the UI where we'd like to place it next to a PrimaryButton.
Outline buttons are a good choice when you want to emphasize an action or choice without overwhelming the user. They're less visually dominant than solid, filled buttons, which is why they are commonly used for secondary or less important actions on a page. We were missing a "ghost" or outline type button from our set of buttons, so this will be a nice addition to our UI Kit. 
The default should have a white background as requested by design, this ensures it has …

feat: new outline button components
